### ISSUE TITLE
Update from repository fails after changed name

### ISSUE THREAD

**Issue by KeyWeeUsr** [OpenUserJs/OpenUserJS.org#1017]
[My script](https://openuserjs.org/scripts/KeyWeeUsr/Top_Repos) doesn't update when I change `// @name` of a script. File name remains the same as it was before. When I tried to edit it manually, instead of editing the script it creates a new one. How can I fix it? I mean... the path to `.user.js` remains the same, it should change only the content, right?

**Comment by Martii** [comment]
> [My script](https://openuserjs.org/scripts/KeyWeeUsr/Top_Repos) doesn't update when I change `// @name` of a script. File name remains the same as it was before.

It won't... OUJS is centric off of `@name`. Changing the name value would mean it's a new script and not linked in.

> How can I fix it?

Reimport it.

**Comment by KeyWeeUsr** [comment]
Ok, then I guess it'll reset the installs counter as it basically creates a new script anyway. Is there a way how to save the counter or at least notify users that a change has been made without doing it manually inside of my old script?

**Comment by Martii** [comment]
> Is there a way how to save the counter

It's considered a new script by most .user.js engines, so no.

> notify users that a change has been made without doing it manually with my old script?

That's the process. I would forward the `@downloadURL` if I were in your shoes... but I usually don't change script names mid-stream.

**Comment by KeyWeeUsr** [comment]
Thanks for your help, I guess reverting the name will be the best solution.
