### ISSUE TITLE
Messed up my user name

### ISSUE THREAD

**Issue by ketilkn** [OpenUserJs/OpenUserJS.org#1056]
Same issue as #886. I messed up my user name. Do you mind removing the gmail-part? Username equals github username + gmailcom. If you prefer to delete my account I am fine with recreating.

**Comment by Martii** [comment]
Not without it linked to GH... while it may look the same I can't verify that it's really you... or drop a note in your profile under the existing account to let me know.

**Comment by ketilkn** [comment]
Thank you for your quick resonse. 

https://openuserjs.org/users/ketilkngmail.com

**Comment by Martii** [comment]
Done... had to delete your script as it's quite a bit faster...  but had it open in another tab and copied it directly.

**Comment by Martii** [comment]
Btw make sure you log out and back in.

**Comment by ketilkn** [comment]
Awesome. Thank you very much.

8. mar. 2017 01.20 skrev "Marti Martz" <notifications@github.com>:
