### ISSUE TITLE
Can’t create new group

### ISSUE THREAD

**Issue by jesus2099** [OpenUserJs/OpenUserJS.org#109]
https://openuserjs.org/scripts/jesus2099/httpsgithub.comjesus2099konami-command/JASRAC._work_importereditor_into_MusicBrainz_+_MB-JASRAC-音楽の森_links_+_MB_back_search_links
I can’t add JASRAC and 音楽の森 groups in the **edit mode**.

**Comment by Dither** [comment]
So many time has been and no progress. :( How about allowing users add whatever tags they want to their scripts which shown on the script's page and make script groups automatically from those tags if there are at least 10 different  scripts from different users in them?
