### ISSUE TITLE
Role elevation failure message

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#1107]
* Not sure how to fix this yet
* Some possible fixes here at http://stackoverflow.com/questions/24430220/e11000-duplicate-key-error-index-in-mongodb-mongoose ... however we won't be dropping the DB. :\\.
* I manually fixed ~80 of these yesterday going back to the beginning of OUJS time. e.g. as early as 2013
* This message has been highly clipped for security reasons:

stderr:
``` sh-session
2017-05-07 11:26:27.143 +00:00: MongoDB User save warning error
abego was NOT role elevated from User to Author with err of:
{
 "code": 11000,
 "index": 0,
 "errmsg": "E11000 duplicate key error index: openuserjs.users.$_id_ dup key: { : ObjectId('*thisObjectIdHashClipped*') }",
 "op": {
  "__v": 0,
  "name": "abego",
  "role": 4,
  "ghUsername": "*clipped*",
  "_id": "*thisObjectIdHashClipped*",
  "sessionIds": [],
  "strategies": [
   "*someAuthStrategy*"
  ],
  "auths": [
   "*clipped*"
  ]
 }
}
```

Current code point where this is generated when storing a script for the first time: [.../blob/`fac5ba5`/controllers/scriptStorage.js#L1253-L1273](https://github.com/OpenUserJs/OpenUserJS.org/blob/fac5ba577e19ad16a2cb9b717d102e8681c1bc36/controllers/scriptStorage.js#L1253-L1273)

Refs:
* #1106 *(another correction to notification)*
* #1105 *(correction to notification)*
* #1098 *(added error trap notification)*

User stat:
```
 Stats

Member since
    8h ago
Number of userscripts
    1
Number of libraries
    0
Total installs
    0
Average installs
    0
Average rating
    0
```

Script stat:
```
Published: 6h ago

Version: 1.0
```

I will go ahead and elevate when these come through but this should be addressed so I don't have more work as Admin. *(Manually elevated user __abego__)*

Cc: @sizzlemctwizzle

**Comment by Martii** [comment]
Fully tested on dev by demoting myself to User then using GH import and does trigger this portion of the conditional... and escalates to Author. Pro keeps me at Admin level which it should since that's outside the initial conditional... but triple checking to be secure.

**Comment by sizzlemctwizzle** [comment]
My best guess is that instead of creating a new duplicate userDoc, retrieve the real one using find(), modify the role, save() it, and in the save callback, call the update method of libs/modifySessions.js to make sure the change is propagated in the session store.

**Comment by sizzlemctwizzle** [comment]
Didn't notice this was already closed. Did your PR take into account saving the modified user doc doesn't propogate the change in role across active sessions?

**Comment by Martii** [comment]
> My best guess is that instead of creating a new duplicate userDoc, retrieve the real one using find(), modify the role, save() it, and in the save callback, ...

This is what the PR does... however...

> call the update method of libs/modifySessions.js to make sure the change is propagated in the session store.

This was never present before or after the PR. e.g. the `new User(userDoc)` ended at that. See [.../pull/1108/files#diff-`b755ddb`L1258](https://github.com/OpenUserJs/OpenUserJS.org/pull/1108/files#diff-b755ddbc6b2edf964c5586d742e3afdaL1258)

> Did your PR take into account saving the modified user doc doesn't propogate the change in role across active sessions?

See last response... e.g. never was there in the first place... understand the logic behind it though... just not sure where in the code to put the session change in. See prior emails about session managements.

> Didn't notice this was already closed

Tiz okay... I follow everything. :) If there is a missing session propagation change a new issue would be preferable since it never existed.
