### ISSUE TITLE
The Install / Source code pages seems currently broken (S3 hanging)

### ISSUE THREAD

**Issue by tzi** [OpenUserJs/OpenUserJS.org#1110]
Hi OpenUserJS Team!

I just wanted to let you know that it seems impossible (for now) to : 
 * Install a new script
 * View source code
 * Update source code

![capture du 2017-05-10 10-51-19](https://cloud.githubusercontent.com/assets/415891/25890673/b1ea5072-356e-11e7-8efe-3d659f0dfb02.png)

Cheers,
Thomas.

**Comment by Martii** [comment]
@tzi 
Thanks for the report... nothing in the stderr logs... but at least my changes have kept MongoDB from posting an empty script homepage.

@sizzlemctwizzle 
S3 is really irking me... will restart the server momentarily... restarted and checked... now it works... this is the issue that prompted me to do changes for the last few weeks... it's still around. :(

**Comment by tzi** [comment]
Thanks for your quick response.

It's OK for me, but I don't if you want to close this issue.
So I let you do as you want! :koala: 

Cheers,
Thomas.

**Comment by Martii** [comment]
@tzi
We'll keep it open for now... apparently nothing I do prevents this yet... I'll add more to it when it appears. 

I do have to take the server down for some quick distro updates though... so if it goes completely out that's why.

**Comment by Martii** [comment]
Done with VPS updates... and restarted again.

**Comment by Martii** [comment]
And there it goes again... absolutely nothing extra in stderr log too. :\ At least it's not a rejection from S3. This adds HOST to the label mix too. The VPS has had connectivity issues off an on but it's up to date and their feed tells me everything usually is resolved.

Will relook into *aws-sdk* package docs and see if we're missing something else.

**Comment by Martii** [comment]
New *aws-sdk* dep from #1114

Server trip:
``` sh-session
2017-05-12 12:05:44.561 +00:00: S3 GET NetworkingError for reek/Anti-Adblock_Killer_Reek.user.js in the *clipped* bucket
```

**Comment by Martii** [comment]
Before reworking the error trap got this *(last restart is scheduled by me when deployed)*:

``` sh-session
2017-05-12 13:22:35.032 +00:00: S3 GET NetworkingError for vulca/topraider.user.js in the *clipped* bucket
2017-05-12 13:22:35.307 +00:00: Starting application...
...
2017-05-12 13:26:07.840 +00:00: Starting application...
```

**Comment by Martii** [comment]
Retesting with *aws-sdk*@2.5.0 manually *(e.g. no process manager)* on VPS session... if the site goes down I'll get to it as soon as I can but need the data it may or may not generate.

Thanks for your patience.

**Comment by Martii** [comment]
Hmmm that was quick... reverted to current HEAD and reinstated process manager e.g. *aws-sdk*@2.49.0

**Comment by Martii** [comment]
Running direct with fe192ebe192c16f13a3b5a5899a805a87b268eb7 and no process manager... again if it trips will restart as soon as possible... need more data.

**Comment by Martii** [comment]
So I think that's about as much as I can think of... we're on a timed run for a few days. *(hopefully)*. If the traps yield what's happening on S3 we can go from there. Appreciate the ears. :smile_cat:

**Comment by Martii** [comment]
Ughh:

``` sh-session
2017-05-15 08:49:51.847 +00:00: Starting application...
2017-05-15 08:49:52.198 +00:00: Starting application...
2017-05-15 08:49:58.646 +00:00: (node:14574) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2017-05-15 08:50:02.533 +00:00: (node:14562) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
```

e.g. nothing, and more nothing... source code is unavailable e.g. nothing was trapped with S3 period... back to the drawing board and restart the server. Didn't even make it one day this time. :\

**Comment by Martii** [comment]
Trying *aws-sdk*@2.51.0 manually on server.... will watch for a bit to see if anything changed.

**Comment by Martii** [comment]
Got a trapping but still a server trip... manually relaunching *(wish *morgan* wouldn't filter these things out)*

``` sh-session
2017-05-16 11:38:39.440 +00:00: S3 GET (establishing)  NetworkingError for vulca/topraider.user.js
{
 "message": "Connection timed out after 120000ms",
 "code": "NetworkingError",
 "time": "2017-05-16T11:38:39.436Z",
 "region": "us-east-1",
 "hostname": "s3.amazonaws.com",
 "retryable": false,
 "statusCode": 200,
 "retryDelay": 66.38535591209418
}
2017-05-16 11:38:39.752 +00:00: Starting application...
```

**Comment by Martii** [comment]
Here's the full, unfiltered from *morgan*, console output:

``` sh-session
S3 GET (establishing)  NetworkingError for reek/Anti-Adblock_Killer_Reek.user.js
{
 "message": "Connection timed out after 120000ms",
 "code": "NetworkingError",
 "time": "2017-05-16T11:57:15.606Z",
 "region": "us-east-1",
 "hostname": "s3.amazonaws.com",
 "retryable": false,
 "statusCode": 200,
 "retryDelay": 52.26317028790848
}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:193:12)
    at PassThrough.Writable.write (_stream_writable.js:240:5)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Restarted with process manager and current HEAD e.g. *aws-sdk*@2.49.0

**Comment by Martii** [comment]
Trying *aws-sdk*@2.51.0 manually launched on server

**Comment by Martii** [comment]
Disk latency not an issue plus wasn't looking forward to not being able to log the trap... I'll do some reversions later today to restore this:

``` sh-session
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:193:12)
    at PassThrough.Writable.write (_stream_writable.js:240:5)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Restarted with process manager and current HEAD e.g. *aws-sdk*@2.49.0

**Comment by Martii** [comment]
@sizzlemctwizzle 
Other than concurrent connections to S3 is there a reason why we're doing `new AWS.S3()` and not just one reusable connection? Is there a limit to the number of concurrent connections to S3?

**Comment by Martii** [comment]
Going to run with this last commit for a bit then try newest *aws-sdk* dep.

**Comment by Martii** [comment]
Seems to have made it past the 7 minute mark and no shakiness... but doesn't mean that S3 won't have errors during higher traffic times. Current uptime is ~34 minutes.

**Comment by Martii** [comment]
Relatively sure this is fixed now...no trips for ~41 hours and no messages in stderr. 

It does appear that chunking from S3 remote to the server is no longer a feature with using S3's error handler. Perhaps down the road it will be available.

Closing. If it reappears please ping here and will reopen to investigate.

Thanks for everyone's patience.

**Comment by Martii** [comment]
Gahh... up 6 days with no incident... however just discovered it hanging again. Reopening and reassigning for more.

**Comment by Martii** [comment]
Hopefully this doesn't hex it... but we've been up for 11 days and no S3 dead zone... but updates will be next week sometime so may affect that timeline.

**Comment by Martii** [comment]
Been up for ~13 days now and a few messages in the console regarding outages of S3 which "self-corrected" after a time... none detected on random manual checks.

**Comment by Martii** [comment]
Other than some S3 messages *(mainly slow down for some users attempting to grab source too many times)* this appears to have normalized. We are watching this but closing again for now.
