### ISSUE TITLE
Please add Violentmonkey to wiki for Firefox and Chrome

### ISSUE THREAD

**Issue by AlexBeLi** [OpenUserJs/OpenUserJS.org#1140]
Because Violentmonkey supported not only Opera.

[Violentmonkey images.zip](https://github.com/OpenUserJs/OpenUserJS.org/files/1050094/Violentmonkey.images.zip)

**Comment by Martii** [comment]
> [Violentmonkey images.zip](https://github.com/OpenUserJs/OpenUserJS.org/files/1050094/Violentmonkey.images.zip)

Nicely done. :) Thanks.

Closed by 78237d40e6f0fb877c208d96cff9e813a882e689 and e06c030dc38852d2449427389c9866801695c7c0
