### ISSUE TITLE
Script no longer autoupdating from GitHub. Also, importing a new script from GitHub results in '400 | Error while importing script'

### ISSUE THREAD

**Issue by darkred** [OpenUserJS/OpenUserJS.org#1247]
Today I've updated [this script](https://github.com/darkred/Userscripts/tree/master/RARBG_-_torrent_and_magnet_links) via [this commit](https://github.com/darkred/Userscripts/commit/d2c0971e1f2316755b1dc1807812a2f17659115d) .
The webhook is ok ([screenshot](https://user-images.githubusercontent.com/723651/32694036-fd66445e-c73e-11e7-9f60-2e5a321ad6fc.jpg)) . _(I've also setup one for greasyfork)_.
But, the script only got updated in [greasyfork](https://greasyfork.org/scripts/23493),
but not in [OUJS](https://openuserjs.org/scripts/darkred/RARBG_-_torrent_and_magnet_links).

Also, I tried importing a new script from my repo in GitHub to OUJS.
So, I got to https://openuserjs.org/users/darkred/github/repo?user=darkred&repo=Userscripts 
and pressed import for the relevant entry ('OpenSubtitles - direct download links') but I got '400 | Error while importing script'.

This is the first time I get these errors.

**Comment by Martii** [comment]
See also https://openuserjs.org/announcements/Licensing_enforcement

**Comment by darkred** [comment]
Thank you for the info and the PR.

**Comment by vanowm** [comment]
@licence is present in my [script,](https://github.com/vanowm/airdates.tv_enhancer/blob/master/Airdates.tv_enhancer.user.js) filename is exactly the same as on OUS, but still getting 400 error


It's probably unrelated, but importing from github just shows this:
![image](https://user-images.githubusercontent.com/511517/32983403-f9b08176-cc61-11e7-8245-63db9f9b0f97.png)

I'm using AOL as login at OUS, might this be a problem?

**Comment by Martii** [comment]
AOL shouldn't have anything to do with it.

Test pass with https://github.com/Martii/UserScripts/commit/88d2cdab2a234b6d0ebd885bf48f8410771bef91#diff-ee6957ae6371b7c46e91f676d279008b as it's on OUJS now.

I'll fork your script and see if it's something I did yesterday. Had lack of sleep but now I'm caught up.

**Comment by Martii** [comment]
Hmmm well source is fine... see https://openuserjs.org/scripts/Marti/Airdates.tv_enhancer that's a fork of your script then I copied the GH source into it. The routine is the same. Now I'll try as you on the site with a GH import.

**Comment by Martii** [comment]
Actually it is indirectly because you don't have GH as an auth... go to https://openuserjs.org/user/preferences and add GH as an authorization. GH will ask you to confirm then you'll be able to import... that's a bug Zren put in that isn't real descriptive.

**Comment by vanowm** [comment]
So the auth also affecting GH webhook?

**Comment by Martii** [comment]
Yes... I'll fix it so if we don't have a confirmed GH username it will send it off to an error page saying you have to add an auth for GH. You can still use AOL as your primary but the server needs to store that confirmation. So add GH as auth then toggle it back to AOL if that is your preference.

**Comment by Martii** [comment]
So there are some notices... I'm going to spend some deep thought, re-querying sizzle more in depth, on whether or not this feature, as is, sticks around. With the OSI `@license` check it's more safe than without but it has the obvious drawback of not being sync-able... and thus the confusion by the site implementation.

**Comment by vanowm** [comment]
And how do we remove auth from our account?

**Comment by Martii** [comment]
You don't.
