### ISSUE TITLE
Failed to login with Google

### ISSUE THREAD

**Issue by eugenox** [OpenUserJS/OpenUserJS.org#1313]
I created an account on openuserjs.org with my Google account a long time ago. Now when I try to authenticate, the login screen properly recognises my username and offers me to sign in. When I do so, I land on "/login?authfail" and I see no other sign of error. The login page looks as if nothing happened.

I tried to remove OpenUserJS from the list of services allowed to access my Google account, and reauthorize the site, but nothing changed.

My Google and GitHub usernames are the same.

**Comment by Martii** [comment]
> I tried to remove OpenUserJS from the list of services allowed to access my Google account, and reauthorize the site, but nothing changed.

This orphans your account under all circumstances.

> I created an account on openuserjs.org with my Google account a long time ago.

Read [this](https://openuserjs.org/announcements/Google_Authentication_Deprecation) from beginning to end... especially the end. You are out of luck. Unfortunately you didn't put on an alternate auth so it can't even be switched.

**Comment by Martii** [comment]
There is one small possibility of recovery... if you put a distinct message on https://eugenox.appspot.com/ and use your GH here to sign up on OUJS... I'll merge the GH account to the account that has the google auth and destroy the google key leaving you to switch at your leisure. If none of this happens, exactly in this order, you are back in the same boat.

**Comment by eugenox** [comment]
Thank you @Martii. I just did what you said. My new account on OUJS is `__eugenox__`, and here is the proof you asked: https://eugenox.appspot.com/script/oujs

**Comment by Martii** [comment]
Completed. Your google auth is destroyed and GH is in its place on the original account. Please remember if you kill an auth strategy side it orphans the account completely... so I would recommend never doing that. Luckily you had just enough of a trace for me to do this. :) Google did this to a bunch of people and it is a face palm every time.

**Comment by eugenox** [comment]
It works. I'm really grateful for your help. Thank you.
