### ISSUE TITLE
Fix login for jhult

### ISSUE THREAD

**Issue by jhult** [OpenUserJS/OpenUserJS.org#1337]
I got bit by the [Google Authentication deprecation](https://openuserjs.org/announcements/Google_Authentication_Deprecation). There are a few traces to me under [my 2 scripts here](https://openuserjs.org/users/jhult).

1. Namespace in source points to my website.
2. Description links to a gist hosted by my Github user.
3. Description links to a blog post on my website.

I can post something to my website (and provide the URL) if that will help confirm me. Any assistance is appreciated.

**Comment by Martii** [comment]
1. Leave a blog post on [your website](https://jonathanhult.com) please... as long as it's not a public forum that others can post to... and where I can find it.
2. I have a few minutes later today *(Friday)* before I leave for the weekend so it may not be until Sunday/Monday.
3. I have to merge something e.g. sign up again on OUJS with GH and let me know that you have and that auth will become primary on the old account after merging.

If all happens then I can merge GH authed account into the old account then destroy new account username and then remove the google auth for you to redo if you so wish.

**Comment by jhult** [comment]
Thanks and done. See the note for you [here](https://jonathanhult.com/blog/2014/11/hide-linkedin-ads/).

**Comment by Martii** [comment]
Done. Ensure that you are https://openuserjs.org/logout of OUJS and then give it a whirl with GH auth again... should be the correct account. You have to let me know if you want the old google auth destroyed so you can recreate it. Policy is to leave it in unless otherwise requested. Will get to that late Sunday if so.... gotta run but can read things here.

**Comment by jhult** [comment]
I am in. Thank you!

You can destroy the old Google auth (so I can recreate it).

**Comment by Martii** [comment]
There you go.
