### ISSUE TITLE
Ignore flagged script

### ISSUE THREAD

**Issue by sizzlemctwizzle** [OpenUserJs/OpenUserJS.org#134]
A button that lets moderators change a script in the flagged state to not flagged. The script would become flagged again on the next update. Perhaps there should be a reset button (setting in the number of flags to zero) for admins if we think a script has been flagged for no reason.

**Comment by Martii** [comment]
With some even more understanding twiddling directly with the database in this area we'll have to `.remove` the associated `Flag`s as well otherwise things get really murky in calculating the rating... and to prevent orphaning of those `Flag`s... still seems a bit overcomplicated UI logic wise.

**Comment by Martii** [comment]
Moved to #642
