### ISSUE TITLE
*passport-steam* failing

### ISSUE THREAD

**Issue by Martii** [OpenUserJS/OpenUserJS.org#1347]
Both 1.0.8, 1.0.9 and the OUJS forks *(commit specified)* are producing `?authfail`.

**Comment by Martii** [comment]
Still failing when deployed via `git`... not sure what to do and I'm outta time for now.

**Comment by Martii** [comment]
Some notes out loud *(may add/change to this)*:

1. This **is directly related** to the non-user profiled session found at #1344 earlier today ... tested on dev and it creates one on auth fail. `sessionStore.clear();` has no effect when the "stuck" session data is removed *(other than logging out everything by removal of the MongoDB session cookies)*.
2. `aLoggedIn` argument at https://github.com/OpenUserJS/OpenUserJS.org/blob/193c04c872473cc0d65e82a63941a2fa2676ecb8/libs/passportVerify.js#L16 shows as `undefined` e.g. blank in console output... which triggers this section at https://github.com/OpenUserJS/OpenUserJS.org/blob/193c04c872473cc0d65e82a63941a2fa2676ecb8/libs/passportVerify.js#L75-L77 which in turns triggers https://github.com/OpenUserJS/OpenUserJS.org/blob/193c04c872473cc0d65e82a63941a2fa2676ecb8/controllers/auth.js#L242-L248
3. Confirmed that https://github.com/OpenUserJS/OpenUserJS.org/blob/193c04c872473cc0d65e82a63941a2fa2676ecb8/libs/passportLoader.js#L37 is set to match docs at [/liamcurry/passport-steam/blob/`92974ba`/README.md#configure-strategy](https://github.com/liamcurry/passport-steam/blob/92974ba3bd6042b4d714e91db6f59412f0804a6e/README.md#configure-strategy)
4. https://github.com/OpenUserJS/OpenUserJS.org/blob/193c04c872473cc0d65e82a63941a2fa2676ecb8/controllers/auth.js#L195-L199 has the right number of parameters according to docs at [/liamcurry/passport-steam/blob/`92974ba`/README.md#configure-strategy](https://github.com/liamcurry/passport-steam/blob/92974ba3bd6042b4d714e91db6f59412f0804a6e/README.md#configure-strategy)
5. Reverted way back to 9688002 in dev... still failing e.g. probable that it's steam site related and/or the dependency *(however since *passport-steam*@1.0.8 doesn't work... it's possibly site related instead)*

**Comment by Martii** [comment]
@sizzlemctwizzle 

I think I've identified the bug... indirectly mentioned in [the above comment](https://github.com/OpenUserJS/OpenUserJS.org/issues/1347#issuecomment-382651808) with:

> Alternatively Steam could have changed their digest auth key algorithm server side before/during/after their http to https migration without our knowledge.

Comparing my digest on pro to the digest from the creation of the new account on dev.... the difference is the `aId` contains `https:...` now instead of `http:...`... and running both, full, values through the crypto routine produces the exact hash key that I need for Steam authentication.

What this means is everyone, **and I do mean everyone, that has Steam as their auth prior to their https switch... their account access with this auth is currently orphaned**... **I do see a potential recovery option** however we should try to figure that part out to keep things private as possible and preferably as smooth as possible *(e.g. right now it is painstakingly lengthy to convert as the values are currently unknown)*

Also there were a few comments on their repo that they "might go back" which will compound the issue.

**Comment by sizzlemctwizzle** [comment]
1. Blindly hash the value we get back from steam and see if it matches the stored hash. If it matches, then login.
2. If not, replace `/^https:/` with `http:` on the value we get from seam. Hash it and see if it matches the stored hash.
3. If it does, hash the the unmodified value we got from steam, and update the hash that we store to this new value. Finally, login.

**Comment by Martii** [comment]
Ref:
* https://steamcommunity.com/discussions/forum/10/1458455461480324749/?ctp=18#c1696043806558481203 for about April 5th, 2018. Too bad they aren't open source and/or didn't announce it on [their Twitter feed](https://twitter.com/Steam_Support). we could pin it down almost to the time they deployed. Will do a stats check to see what was made with Steam after that.

**Comment by Martii** [comment]
My steam account migrated well on pro... So if the users on OUJS are observing this issue and have an existing steam account please login it even if it's just for a moment. This is a two time login migration. Single would have entailed a rather large rewrite and the recovery won't be in there forever imho. e.g. it has at least 6 months before it should be removed to allow those users to recover.

I would like to have a few days *(and see some users doing it in stdout)* before turning off readonly for new/attached steam accounts.

**Comment by Martii** [comment]
Finally one user migrated besides me... not a very used passport.

**Comment by Martii** [comment]
Still only myself and one other that has recovered their Steam auth... as of today...

**Comment by Martii** [comment]
Closing but mitigation label still active.
