### ISSUE TITLE
Source code viewer has tiny height

### ISSUE THREAD

**Issue by sizzlemctwizzle** [OpenUserJs/OpenUserJS.org#136]
@Zren 

This was only thing I caught when testing  #129 but it wasn't enough to prevent me from merging and deploying. ~~It happens when not logged in.~~

[![Screenshot](http://i.imgur.com/OEHSU5d.png?1)](http://imgur.com/OEHSU5d)

**Comment by Martii** [comment]
Closing from #503 and #505 ... reopen if necessary.

**Comment by jesus2099** [comment]
Thanks very much, @Martii !
I unfortunately hadn’t notice your fix earlier than yesterday (jesus2099/konami-command@37c5bd219e4749e9016fc4277ea1b486fc3752a0).
That’s working great !
