### ISSUE TITLE
markdown on script info page not working

### ISSUE THREAD

**Issue by trespassersW** [OpenUserJS/OpenUserJS.org#1499]
what I see now:
<pre><code>| | |
| :---: | :---- | 
| <img src=https://i.imgur.com/8buFLcs.png >  |
</code></pre>

**Comment by Martii** [comment]
*marked* is having some growing pains and pending releases... use `| &emsp; | &emsp; | &emsp; |` for your table header and it should be fine.

**Comment by trespassersW** [comment]
Ye <code>&emsp</code> helped. And yes. i don't want to show my real  userAgent, for some reasons (now I do not remember them ;)

**Comment by Martii** [comment]
Not a problem... enjoy sending your cookies to other links ;) Closing as non-OUJS issue.
