### ISSUE TITLE
GitHub Service Hook

### ISSUE THREAD

**Issue by sizzlemctwizzle** [OpenUserJs/OpenUserJS.org#16]
We can get OpenUserJS listed as an [official service hook](https://github.com/github/github-services), which will make integration simpler for users than a WebHook (#2).

**Comment by marsjaninzmarsa** [comment]
More like Integration, new Service Hooks are no longer accepted.
https://github.com/integrations

**Comment by Martii** [comment]
@marsjaninzmarsa 

> More like Integration, new Service Hooks are no longer accepted.
https://github.com/integrations

Thanks.

Ref:
* https://github.com/github/github-services#current-status <sup>[/github/github-services/blob/`4023f8e`/README.md](https://github.com/github/github-services/blob/4023f8e34ff35ec1ed521353aba6816f0baf6622/README.md)</sup>

@sizzlemctwizzle 
This should probably be closed... reopen if needed or better yet a new issue as the subject intent will change. I would be :-1: for adding tools to the global namespace on production that might observe what a user is doing on OUJS.

**Comment by Martii** [comment]
Marked for deprecation at:
* https://blog.github.com/changelog/2018-04-25-deprecation-github-services/
* https://github.com/github/github-services/blob/99cac3e2208ccccd09225451986b7800058414f0/README.md#github-services

Two conflicting end of life dates of 2019-01-31 and 2018-10-01 ... Glad we never relied on this. Canceling reopening and setting to `wontfix`.
