### ISSUE TITLE
"Specified file does not contain the proper metadata blocks."

### ISSUE THREAD

**Issue by narthur** [OpenUserJS/OpenUserJS.org#1637]
I'm trying to import this file from GitHub:

https://github.com/narthur/bm-opener/blob/master/bm-opener.js

But every time I get the following error:

> Specified file does not contain the proper metadata blocks.

It doesn't tell me what is missing or broken in my meta block.

What am I doing wrong?

**Comment by Martii** [comment]
> What am I doing wrong?

Please give a read at https://openuserjs.org/about/Userscript-Beginners-HOWTO#what-is-a-user-script-

How to correct... `git mv bm-opener.js bm-opener.user.js`

**Comment by Martii** [comment]
Made a PR for your evaluation on each step I described above. Then please reimport from GH to OUJS to establish the linkage for everyone.

**Comment by narthur** [comment]
Thank you for the help! I think I can take it from here. :)
