### ISSUE TITLE
Create good MVC base for app

### ISSUE THREAD

**Issue by cletusc** [OpenUserJs/OpenUserJS.org#17]
We need a good MVC base for the app, with folder structure looking something like so:

```
root
    controllers
    models
    node_modules
    views
    public
        js
        css
        images
    app.js
    package.json
```

**Controllers:** Handles all logic, db calls, etc and is used directly by our routes using something like `app.controllers.[category].[specific route]` (e.g. `app.controllers.scripts.raw` to handle the `.user.js` and `.meta.js` routines).

**Models:** Complete schema data and db-specific logic here, which would most likely use [mongoose](http://mongoosejs.com/) to make it easier.

**Views:** All templates. Hook into using express's `view engine` and `views` so that we can easily call `res.render([viewname], [data])`.

**Public:** All the frontend publicly visible stuff.

---
## Opinion needed

What extension should we use for templates (which will be Mustache)? Some sites I've seen use `[file].mustache` and others `[file].tpl`. I'd prefer `.tpl` in case we ever switched template engines down the line.

**Comment by Martii** [comment]
FYI

This is the generic, wip, structure that has been observed since entry *(e.g. a visual aid for reference)*:

![MVC Exemplar](https://raw.githubusercontent.com/wiki/OpenUserJS/OpenUserJS.org/images/mvcExemplar.png)

We don't quite follow this completely but it is the goal none-the-less.
