### ISSUE TITLE
Provide shields.io badges

### ISSUE THREAD

**Issue by NatoBoram** [OpenUserJS/OpenUserJS.org#1755]
As a script developer, I want to show off the install count of my userscript on its Git repository. Because there's no API (https://github.com/OpenUserJS/OpenUserJS.org/issues/77), I can't create my own badge with shields.io's API (https://github.com/badges/shields/issues/5505).

Example :

[![GreasyFork](https://img.shields.io/badge/dynamic/json?color=%23990000&label=GreasyFork&query=total_installs&suffix=%20installs&url=https%3A%2F%2Fgreasyfork.org%2Fscripts%2F411035.json)](https://greasyfork.org/scripts/411035)

---

**OWNER EDIT** for feature request:

Ex. `[![GreasyFork](https://img.shields.io/badge/dynamic/json?color=%23990000&label=GreasyFork&query=total_installs&suffix=%20installs&url=https%3A%2F%2Fgreasyfork.org%2Fscripts%2F411035.json)](https://greasyfork.org/scripts/411035)`

**/OWNER EDIT**

**Comment by Martii** [comment]
Hmmm this seems to work already with Shields.

`[![OpenUserJS](https://img.shields.io/badge/dynamic/json?color=%23990000&label=OpenUserJS&query=%24.OpenUserJS.installs%5B%3A1%5D.value&suffix=%20installs&url=https%3A%2F%2Fopenuserjs.org%2Fmeta%2FNatoBoram%2FYouTube_Comment_Blacklist.meta.json)](https://openuserjs.org/scripts/NatoBoram/YouTube_Comment_Blacklist)`

The actual query unencoded:
`$.OpenUserJS.installs[:1].value`

[![OpenUserJS](https://img.shields.io/badge/dynamic/json?color=%23990000&label=OpenUserJS&query=%24.OpenUserJS.installs%5B%3A1%5D.value&suffix=%20installs&url=https%3A%2F%2Fopenuserjs.org%2Fmeta%2FNatoBoram%2FYouTube_Comment_Blacklist.meta.json)](https://openuserjs.org/scripts/NatoBoram/YouTube_Comment_Blacklist)


Refs:
* [JSONPath Online Evaluator](https://jsonpath.com/) ... teaching a dog new tricks... Thanks for the reference over there.
* [URL encoder/decoder for QSP values](https://www.urlencoder.org/)

**Comment by Martii** [comment]
Closing per https://github.com/badges/shields/issues/5505#issuecomment-690610106
