### ISSUE TITLE
How to import script from GitHub?

### ISSUE THREAD

**Issue by HaleShaw** [OpenUserJS/OpenUserJS.org#1762]
While I import a script from GitHub, it returned 400.
I've tried many times. I've added so many metadata for the script, but the error is still existing.
I've tried using scripts that others have successfully imported, and the error didn't disappear.

What should I do?
Could it display more detailed error messages?

![image](https://user-images.githubusercontent.com/32861865/93546316-21290080-f995-11ea-90c5-1c6b9054c0cd.png)

**Comment by Martii** [comment]
> What should I do?

See your issue on your repo.

> Could it display more detailed error messages?

Nope. The metadata blocks are something that should be forrmatted properly in all .user.js ... as I mentioned over on your issue please give the Userscript Beginners HOWTO a good, quick, reading.
