### ISSUE TITLE
How to inject styles into iframe generated by a chrome extension

### ISSUE THREAD

**Issue by ErinPo** [OpenUserJS/OpenUserJS.org#1766]
The Chrome extension creates an iFrame like so:

`<iframe src="chrome-extension://okjpocelpnlfdi/app.html"></iframe>`

I tried to match it in Tapermonkey v4.10 using:

// @match  chrome-extension://*
// @match chrome-extension://oknpjjbmpnndlpmnhmekjpocelpnlfdi/app.html

but the script never gets triggered. Does anybody know how to get it to work?

**Comment by Martii** [comment]
Thanks for reaching out however this is development. Try asking your question on production at https://openuserjs.org/garage
