### ISSUE TITLE
Can't sign up to site with This github account?

### ISSUE THREAD

**Issue by MPThLee** [OpenUserJS/OpenUserJS.org#1768]
Hello, I was trying to sign up OpenUserJs.org. But it keeps failing. (back to `/login?authfail`)
It was first authorized with this github account. in 30 minutes of this issue creation. I think?
I tried to find some contact on site(like a email way), But seems can't do that because even discussion requires account.

Sorry for using issue tabs for this problem. Maybe I signed up sometime even I can't remember. But I think it's not as i mentioned earlier. It shows first authorized page on github side.

**Comment by MPThLee** [comment]
Just trying to searching issues and maybe #1705 is related? I tried to search about `sign up` but there wasn't issue about it.

**Comment by Martii** [comment]
The issue is that you broke the TOS by posting obfuscated scripts after we got a report. This account is banned permanently for TOS violation. Oct 15, 2018 is when the action was applied.
