### ISSUE TITLE
Can I still restore my openuserjs account?

### ISSUE THREAD

**Issue by ghost** [OpenUserJS/OpenUserJS.org#1770]
-

**Comment by hybridsong** [comment]
![Screenshot_20201017_141229](https://user-images.githubusercontent.com/64523036/96329819-ed6bf400-1082-11eb-8428-6e08fff585ed.png)

**Comment by Martii** [comment]
This is a toughie... I'd have to say you need to contact GH to see if you can get the same authorization back. You'll probably need to have the same email address back then too. I'll send out a feeler to sizzle but I'm going to have to think about this one to see if I can find anything that I can do from my end. As you are aware it's not just your username that GH registers and we don't check usernames we check authentication tokens that we get back. So if GH is giving you a different one then you need to talk to them first to hopefully get it squared away. I'll keep thinking if there's something I can investigate but no promises.

**Comment by hybridsong** [comment]
I can make sure that this openuserjs account is me, and I can also be sure that no one will ever log into this openuserjs account again. Looking for github to restore the authentication tokens I think is almost impossible. Can you just compromise on this matter? Thank you.

**Comment by hybridsong** [comment]
I currently have 2 Github accounts registered, one with the same email as openuserjs registered and the other with the same username. I tried each account and could not log in. OAuth does not seem to check either the email address or the username.

**Comment by hybridsong** [comment]
To be honest, I can't remember exactly which email address registered the GH account for the openuserjs account. Do you have the email address recorded in website database? I'll probably provide you with 2-3 email addresses (because I'm not sure) to confirm my identity.

**Comment by Martii** [comment]
> I can also be sure that no one will ever log into this openuserjs account again

The auth tokens GH uses are never reused as far as I know... and most likely as you know since your token here doesn't match what we stored of it back then for that account.

> Can you just compromise on this matter? 

We need to validate you somehow otherwise it won't happen. You can continue to message here or I can continue to look for alternate ways to see if validation is possible. Your choice.

> Do you have the email address recorded in website database?

No.

> I'll probably provide you with 2-3 email addresses

Providing GH with this is the way to go because we don't store those.

**Comment by hybridsong** [comment]
I asked for the GH support and following is the response

GitHub Support: "Thanks for reaching out. I'm afraid that removed/destroyed tokens can't be restored."

Is there any other way? I just want to delete the Openuserjs account.

**Comment by hybridsong** [comment]
I don't seem to have any way to verify the identity, the only thing I can confirm is that this account will never be logged in again in the future. My request is also simple, delete the account. I hope you can help me with this issue. I just forgot I had other related accounts when I deleted my GH account at the time.

**Comment by hybridsong** [comment]
Wait... I've found a way through.
[Source1](https://openuserjs.org/scripts/hybridsong/Enhanced_Image_Boards/source) [Source2](https://openuserjs.org/scripts/hybridsong/Enhanced_SauceNao/source) at namespace line.
The above is the last code I updated which contains the address of my GH account.
I wonder if this will verify my identity. Thanks.

**Comment by hybridsong** [comment]
[Source1](https://openuserjs.org/scripts/hybridsong/Enhanced_Image_Boards/source) [Source2](https://openuserjs.org/scripts/hybridsong/Enhanced_SauceNao/source)
The above code contains my Github account information, can this confirm my identity? If not, I would like to be able to delete the account after a period of time, as I will never log back in.
Thank you.

**Comment by hybridsong** [comment]
https://openuserjs.org/users/hybridsong/scripts
There are 3 scripts that contain my Github address, can this confirm my identity? If not, I would like to be able to delete the account after a period of time, as I will never log back in.
Thank you.

**Comment by Martii** [comment]
To answer your question... we can't validate that it's you. So no you can't.
