### ISSUE TITLE
Facebook Dep: Not possible log-in to system

### ISSUE THREAD

**Issue by Vylda** [OpenUserJS/OpenUserJS.org#1786]
I try log-in to system, but an every login service redirect to Facebook and messages is on screen: login service is not available (in Czech). Redirected to 502 error page. Any solution?

**Comment by Martii** [comment]
> Any solution?

That is a dependency at https://github.com/jaredhanson/passport-facebook/issues ... seems there might be an issue either with FB or the dep. Can't do much about it until the maintainer or FB notifies. Will track upstream though.

**Comment by Vylda** [comment]
Hmm, it is not good news. Last commit 8 months ago...

**Comment by Martii** [comment]
OAuth passports don't usually change a whole lot unless it's in the back-end... so commit history doesn't mean as much.

**Comment by Martii** [comment]
This is problematic just in my general twiddlings with auths recently. Yes I've emails @sizzlemctwizzle again. \*le sigh\*

**Comment by Martii** [comment]
Well the news is in... this dependency is now in the past tense. 

No support will be given and if you didn't add an alternate account then it's orphaned.

Sorry folks.
