### ISSUE TITLE
Webhook sync fails with a 403 error 

### ISSUE THREAD

**Issue by monk-time** [OpenUserJS/OpenUserJS.org#1791]
I have configured a GitHub webhook in [my repo](https://github.com/monk-time/userscripts) that contains multiple userscripts to that the site can auto-update three of them that I have [uploaded there](https://openuserjs.org/users/monk-time/scripts). The ping event was delivered successfully but [the actual push](https://github.com/monk-time/userscripts/commit/b38f034874a7f90d73581c126218504e0a1b32f7) fails with a 403 error:

![image](https://user-images.githubusercontent.com/7759622/114306964-51c5b880-9ae6-11eb-81bf-79566679e2b7.png)

I highly suspect this is caused by me having `main` as my default branch name. I have found another issue here about the same problem (https://github.com/OpenUserJS/OpenUserJS.org/issues/1781), but it's locked because of what seems like a major misunderstanding. 

Regardless of the maintainers' position re: the name of OpenUserJS.org default branch, it would be great if sync could be fixed to work with repos that have `main` as their default branch name. AFAICT that would require adding `payload.ref !== 'refs/heads/master' && payload.ref !== 'refs/heads/main'` here:

https://github.com/OpenUserJS/OpenUserJS.org/blob/0e6ec485c935856ba8f120eef8fad4a13de5f248/controllers/scriptStorage.js#L2181-L2185

**Comment by Martii** [comment]
Apparently this needs to be ckarified thrice... duplicate of #1781.

Also read labels and milestones. It is almost never as easy as a one liner... so don't be naive please. The other issue is open and will be addressed in due time. Do **not** open duplicate issues or tack on to a closed issue... this policy will be enforced completely in the next few days.
