### ISSUE TITLE
Allow reporters to respond on their own issues

### ISSUE THREAD

**Issue by monk-time** [OpenUserJS/OpenUserJS.org#1792]
I've been frankly appalled by issue moderation on this repo. Politely worded issues get closed without any explanation (#1791), and there's no chance to reply or discuss previous decisions or ask for clarification as issues also get discussion-locked instantly. Four pages of closed issues got locked for no apparent reason in the last hour. My comment on #1610 that was asking for elaborations on technical matters got removed without an explanation. Circumstances can change (as I mentioned in the deleted comment), a closed issue can become relevant again, I don't understand why it is not allowed here to comment on them. 

I opened my issue as I didn't understand @Martii's reply on #1781 and naturally assumed (as I mentioned in my issue) that the maintainer interpreted the issue in a totally different way than the reporter intended. There's no other way I could've connected a minor and reasonable request in that issue with an uncalled-for and over-the-top reaction that it had received. I apologize for opening a duplicate issue, atm I didn't see it as a duplicate and I couldn't ask before opening it as #1781 also was discussion-locked.

I don't see any Code of Conduct here so I assume common GitHub rules apply, and usually one can see this type of reaction only after a commenter has violated civility rules in their comments. I don't believe I have done so but the treatment I have received indicates otherwise. Honestly to me that whole interaction with not giving a chance to engage in a civil discussion felt extremely rude. I got treated as a criminal for reporting a bug and asking about the reasoning behind an implemented restriction and whether it can be reconsidered.

**Comment by Martii** [comment]
Good morning,

See also:
* https://github.com/OpenUserJS/OpenUserJS.org/blob/master/.github/CONTRIBUTING.md
* https://github.com/OpenUserJS/OpenUserJS.org/blob/master/views/includes/documents/Terms-of-Service.md

As was clarified, now four times, and you persisted...  you have ignored the response to your duplicate and now are on a time out for 30 days. If you continue to violate the TOS and our contributing guidelines you will be perma-banned. You do have a history. 

Please go have a "cup of coffee" and think about how to improve your attitude towards the OUJS management and perhaps you might come back with more constructive issues.
