### ISSUE TITLE
Why is Unlicense not accepted?

### ISSUE THREAD

**Issue by agj** [OpenUserJS/OpenUserJS.org#1809]
Hello! I tried adding my userscripts in my Github repo. Their metadata is `@license Unlicense`. [This is one](https://github.com/agj/agj-userscripts/blob/master/taiwan-isrc-to-musicbrainz.user.js), for instance.

However, I get a 400 error with the message:

```
`@license` is not OSI primary and compatible in the metadata block(s).
```

After doing some digging in your codebase, I figured out [it's a blacklisted license](https://github.com/OpenUserJS/OpenUserJS.org/blob/6ec87e9655e005a614f8333782df9b25ecb87b92/libs/blockSPDX.json). Why is that? Also if the error message was more informative it'd be a big help figuring out the problem…

**Comment by Martii** [comment]
See https://opensource.org/faq#public-domain which is what `unlicense` falls under.
