### ISSUE TITLE
Not able to submit new userscript

### ISSUE THREAD

**Issue by trumpeta** [OpenUserJS/OpenUserJS.org#1845]
**What happened?**

I want to create a new library, I choose Add Library => Write Script Online and paste the source code., but receiving either ERR_CONNECTION_CLOSED, ERR_EMPTY_RESPONSE or HTTP 503 Service Unavailable.

**What did you expect to happen?**

Normally the submitted userscript info page opens with url links for @require etc...

**What the problem might be**

Site bug or connection. No idea. I tried with different browsers and from different networks, no difference in the response. There may be problem with the POST request since when I try to submit empty textbox, I get regular HTML page with error 400.

**Comment by Martii** [comment]
Works for me... see https://openuserjs.org/libs/Marti/RFC_2606%C2%A73_-_Hello%2C_World!_(lib)

Post in your metadata blocks only in a code fence here and I'll see if there's an issue.

**Comment by Martii** [comment]
Btw I'm showing that you haven't logged-in over a year.

**Comment by Martii** [comment]
Closing for non-response.
