### ISSUE TITLE
Arbitrary restriction

### ISSUE THREAD

**Issue by sjehuda** [OpenUserJS/OpenUserJS.org#1952]
Some obsolete scripts with high ratings appear on top of results and main page.

**What’s missing?**
Arbitrary way to downgrade a script to bottom of results.
This feature will be available for Admins on;y.
1. [Script](https://openuserjs.org/scripts/FuSiOn/Warez-BB_+) is obsolete because website doesn't exist anymore, but is rated high which means that it still holds on the main page.
2. Down voting just because of the above reason might be considered as an insult.
3. Once the script is updated, the arbitrary restriction will be void and script will be re-positioned to where it was before the restriction.

**Why?**
To vacant space to other scripts.

**Alternatives you tried**
No.

**Comment by Martii** [comment]
We're not going to be like Apple *(at least from my point of view)* and have an inept decision on forcing people to update potentially working scripts. Besides there are other factors as well. The systems are in place for forking... grab the glory if a script doesn't work by properly forking it if the Author doesn't reply.

**Comment by sjehuda** [comment]
I agree. And I really do!

Please consider these:

1. If the author want to get his suserscript back to where it was, then he simply need to update it, and the restriction will be gine automatically.

2. When I see an outdated userscripts on the first pages of OUJS, it feels like the website is outdated and userscript irrelevant., even though this is definitely not the case, only a feeling.

Feeling influence us.
