### ISSUE TITLE
can't reach openuserjs.org website.

### ISSUE THREAD

**Issue by rezad1393** [OpenUserJS/OpenUserJS.org#1987]
### What happened?

for more than a week I cant seem to be able to reach openuserjs.org even with Tor browser.

### What did you expect to happen?

should be accessible? 

### What the problem might be?

I thought that maybe my ISP is blocked but I cant reach website with Tor.

**Comment by Martii** [comment]
I check it a couple of times a day and it's up. Try a clean chromium/chrome, edge, or firefox browser profile *(you don't have to blow away your existing running one)*.

As I have no way of knowing who/where you are I can't tell you if your ISP is blocked. If your system *(or someone in your network)* is overloading the limiter then it will of course be blocked. Check your machine for malware including any .user.js that is misbehaving... hence why you should try at least a clean browser profile.

**Comment by rezad1393** [comment]
I have tried from command line.
also from my phone via 4g network too
it could be my country (iran) government messing with it, but when I try with tor browser too it fails.
