### ISSUE TITLE
Need to use GitHub as an authentication type is hidden behind having GitHub as an authentication type.

### ISSUE THREAD

**Issue by nexushoratio** [OpenUserJS/OpenUserJS.org#2001]
### What happened?

I was trying to figure out how to set up a GH webhook, and could find no information on it.  Even on the `New Script` page, the information was not there.

I would have added screen shots, but in trying to debug, I logged out of OpenUserJS, and now getting a 429 error logging in.  If I remember the next time I'm logged in, I'll try to reproduce with screen caps.

### What did you expect to happen?

I expect to learn about needing GH as an authentication type without having it already set up.

### What the problem might be?

The portion of the documentation that tells the user they need to have GH authenticated is behind GH authentication.

The line that tells the user what they need to know: https://github.com/OpenUserJS/OpenUserJS.org/blob/cc9595a44fd9adb8986180b0664b01636d761384/views/pages/newScriptPage.html#L357

The rendering directive:  https://github.com/OpenUserJS/OpenUserJS.org/blob/cc9595a44fd9adb8986180b0664b01636d761384/views/pages/newScriptPage.html#L341

**Comment by Martii** [comment]
A [FAQ](https://openuserjs.org/about/Frequently-Asked-Questions) may be created to address this. Non-GH users shouldn't be bothered with this sort of thing in their UI.

PR is welcome with some feedback of course since the link will be rather permanent.
