### ISSUE TITLE
Unsure how to remove an authentication type.

### ISSUE THREAD

**Issue by nexushoratio** [OpenUserJS/OpenUserJS.org#2002]
### What happened?

I'm not sure if this is a bug, or a feature request.

In trying to reproduce #2001 , I wanted to disconnect my GH account from my OpenUserJS account.

I am currently unable to log into OUJS to get a screen cap.

### What did you expect to happen?

I expected there to be a simple way to remove an authentication.

### What the problem might be?

Not implemented or difficult to find.

**Comment by Martii** [comment]
You don't. That is intended behavior. Any removal is on strategy side only for security reasons.
