### ISSUE TITLE
Add the bootswatch fork to OpenUserJS Organization

### ISSUE THREAD

**Issue by Zren** [OpenUserJs/OpenUserJS.org#223]
https://github.com/Zren/bootswatch-OpenUserJS.org

This is the source code for `/public/css/bootstrap-custom.css`

The `custom/build.sh` will build & copy the generated file to OpenUserJS.org repo (both repos must have the same parent folder).

The base bootswatch theme seems to have updated 3.1.1 -> 3.20 since I forked it, probably gonna have to take a look through their changes, but the current theme works fine.

**Comment by Martii** [comment]
@Zren 
With #544 in place and effective we really don't need to do this. Also you mentioned we might be moving away from *bootswatch*... which implies we shouldn't do this.

I'm still not clear on what *bootswatch* really offers. With a clean *bootstrap* theme and adding our colors into a fictional `oujs-theme.less` and ordering it into `oujs.less` we would have what appears to be the stock *bootswatch*. Does it offer some additional classes that aren't in *bootstrap*? When I stripped out *bootswatch* from *bootstrap* other than coloring it appeared exactly identical UI wise.

**Comment by Zren** [comment]
No.  Close this.
