### ISSUE TITLE
More modals needed for confirmation

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#261]
Currently when sending something to the graveyard we aren't giving an option to cancel/close.  Also setting the "Reason" why... it would be helpful to have a modal popup, similar to Delete Script, to enter in the reason.

We do currently have allocated in the DB a space for this but we aren't utilizing it.

Flagging could also have a reason stored but I don't currently see that capability.

---

##### Progress

* [x] Basic modals on User and Script removal
* [x] Reason in modals *(See also https://github.com/OpenUserJs/OpenUserJS.org/issues/261#issuecomment-48852243)*
* [x] Default reasons datalist *(See https://github.com/OpenUserJs/OpenUserJS.org/issues/261#issuecomment-69467296 and useful to narrow results for #490)*

**Comment by Martii** [comment]
There are currently a few possibilities to get this particular issue closed:

1. Do nothing with the data list and let a user.js handle this on a per Moderator and up basis.
2. Add the data list into the `scriptModals.hmtl` and `userModals.html` ... this could help prospective Moderators and up to standardize on nomenclature, less typing, and easily searchable/sortable but also increases that particular modal view.
3. Add the data list into a json and read in dyanmically... this presents the issue of file naming and where to put the .json file. If this is done please mention the file name structure and where. This could also help prospective Moderators and up to standardize on nomenclature, less typing, and easily searchable/sortable.
4. Something else?

Opening up to needs discussion to put in others 2 cents. Please note if I don't get a response I may end up deciding on what to do here. e.g. this is a pseudo poll. Thanks.

**Comment by sizzlemctwizzle** [comment]
I like 3 the best, but 2 seems easier to get up and running. My suggestion is to start with 2 and eventually use 3.

**Comment by Martii** [comment]
Agreed on 3... I finished 2 a little while ago and refinished 3 in separate commits. With that process that helped me figure out where the "optimum" placement of the .json files should go I think plus an epiphany on it's structure/inclusion too. :) Thanks @sizzlemctwizzle 

Publishing PR shortly.

**Comment by Martii** [comment]
Heh... GH currently has the commit references backwards. :\

**Comment by Martii** [comment]
;) Now they've fixered the reference order of commits... love being watched! Good thing I saved a snapshot of when it was backwards. ;)
