### ISSUE TITLE
Guests can see reply button in forum, resulting in 404 after posting

### ISSUE THREAD

**Issue by jerone** [OpenUserJs/OpenUserJS.org#326]
Steps to reproduce:
1. Log out
2. Go to forum post (e.g. [https://openuserjs.org/announcements/Welcome!!!](https://openuserjs.org/announcements/Welcome!!!))
3. Press "Reply" button
4. Type something
5. Press other "Reply" button
6. See 404 page

Two solutions:
1. We hide/disable the "Reply" button for guests. Easy and fast.
2. We link the "Reply" button to the login page for guests. A little harder, because guests won't automatic return to the discussion again after logging in.

**Comment by svishal** [comment]
test
y4yrengfn hmntr 
t
