### ISSUE TITLE
Add Google Analytics / Server Side Tracking

### ISSUE THREAD

**Issue by Zren** [OpenUserJs/OpenUserJS.org#339]
We're getting 503s atm, and it would be good to know how much traffic we're getting to contributes to this. Not sure if @sizzlemctwizzle has server side tracking setup, but we can add something clientside.

Since we're serving static content on the same server, a 503 on a static content request will usually cause the UI to go unstyled.

**Comment by Martii** [comment]
@sizzlemctwizzle 
I've got a local branch with the fixes ready if you want... let me know if you want me to reassign to me for that.

**Comment by sizzlemctwizzle** [comment]
Yeah, you can take it.
