### ISSUE TITLE
Rating Cast Bug

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#340]
#338
> Yes you can... click the rate you chose again and it deselects.

If that's the case then there's a bug. I tried to remove my vote and instead of removing it, it went from a positive vote to a negative one with one click. I was unable to deselect. Tested if on FireFox and G-Chrome.

**Comment by Martii** [comment]
>>   PS: Delete my ... account.

> You now have a permanent test account until...

@TimidScript 
Did you still want to delete that other account on OUJS?

**Comment by TimidScript** [comment]
Sorry for the late reply. You might as well leave it. I used it a few times since then for testing the site.
