### ISSUE TITLE
The site is Malicious - that nasty warning

### ISSUE THREAD

**Issue by moshmage** [OpenUserJs/OpenUserJS.org#399]
Hey, I felt compelled to warn you guys that (for some reason) Chrome seems to think you guys are malicious. But I know you're not, you're the cool kids from the neighborhood ;D

![screenshot](http://i.imgur.com/V7RPjFL.png)

**Comment by ssokolow** [comment]
> I also find these filtering services ironically amusing... "allow google (or some other entity) to track everything you do but no one else"... that spells monopoly and unfair trade practices.

To be fair, Mozilla goes out of their way to mask what you're doing when making SafeBrowsing requests in Firefox:
http://feeding.cloud.geek.nz/posts/how-safe-browsing-works-in-firefox/
