### ISSUE TITLE
Amend TOS for libraries

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#418]
Require those that are using cross-site compatible UserScript metadata block in libraries to have:

```
// @exclude *
```

... in their metadata block. Granted we don't programmatically read these in but administration does.

Applies to:
- https://openuserjs.org/about/Terms-of-Service#licensing

Affects:
- https://openuserjs.org/users/arcum42
- @cvzi
- @JensBee
- @Smiljan
- @TimidScript
- @boneskull
- @emsquared-inc

Refs:
- https://github.com/Galch24/galch/issues/1
- https://github.com/Galch24/greasemonkey-galch/issues/1
- https://github.com/jimmygoings50/Userscripts/issues/1
- https://github.com/swordf1zh/prensa.com-cleaner/issues/1
- https://github.com/tsaiid/gm-ck101-auto-thank/issues/1
- https://github.com/boneskull/bricklink-scripts/issues/1

**Comment by WoLpH** [comment]
Where can I configure this without renaming the files and with that breaking links on other sites as well?
There should be a config option for this somewhere, right?

**Comment by Martii** [comment]
> Where can I configure my userscripts to be scripts instead of libraries without renaming the files?

You don't.

> Renaming the files will break the links on other sites so there has to be a settings somewhere, right?

Correct it will break your links elsewhere and there is no settings as per the .user.js standard of file naming. See [What is a User Script?](https://openuserjs.org/about/Userscript-Beginners-HOWTO#what-is-a-user-script-) versus [What is a Library Script?](https://openuserjs.org/about/Userscript-Beginners-HOWTO#what-is-a-library-script-).

**Comment by WoLpH** [comment]
Ok, guess I will just add a symlink for OUJS in that case :)

**Comment by Martii** [comment]
> guess I will just add a symlink for OUJS in that case

That may work for GH however I am pretty sure that OUJS won't be dereferencing those on import... time will tell. I suggest backing up your source as I won't be.

There will be a one time "gentle" removal but after that if a sync/upload/write happens those libraries not following the Terms of Service announcement will be permanently removed from the libs section and not be allowed to be uploaded again.

**Comment by WoLpH** [comment]
The OUJS version is a backup (it's linked from github) so backing up the
backup seems a bit pointless ;)
As far as I can see only one of my scripts is affected which has no users
on OUJS anyhow so the removal shouldn't be a problem.

Is there any way to see which scripts are affected, the OUJS interface
appears to be slightly incomplete.
When I look at my scripts section I see 4 items in the list while the
scripts badge at the top shows 3. The "Number of scripts" at the right also
shows 3 and the "Number of libraries" shows 0. So I'm guessing one of them
has been soft-removed or something as it's not within any of the lists.

**Comment by Martii** [comment]
> Is there any way to see which scripts are affected

Look for a `&ndash` *(e.g. &ndash;)* which are your libraries. If they don't include an `@exclude *` they will be removed tomorrowish.

> So I'm guessing one of them has been soft-removed or something as it's not within any of the lists.

It's been flagged so those won't show for anyone but moderators up plus you.

> the OUJS interface appears to be slightly incomplete.

If you think the UI can be improved please submit your idea as a new issue and it will be considered. :)

**Comment by Martii** [comment]
[Final comment](https://openuserjs.org/announcements/TOS_Changes#comment-14ac22d58e2) regarding this TOS change on OUJS.
