### ISSUE TITLE
Share script on social media

### ISSUE THREAD

**Issue by jerone** [OpenUserJs/OpenUserJS.org#419]
Ability to share a script on any social media platform.

This would benefit script authors to get more attention to their scripts. Which results in more visitors for OUJS.

Sharing information:
- link to script page
- title of script
- script author
- script description (when available and possible)
- script icon (when available)

Sharing on:
- Facebook
- Twitter (script description should be truncated)
- Instagram
- LinkedIn
- ...

**Comment by GreenLunar** [comment]
We really need to be cautious about this and also be ready to be subjected to censorship, at least on the closed and centralized social networks.  It would be easier to start off with decentralized and free social networks such as diaspora*, GNU Social, Hubzilla, Movim, RedMatrix, Salut à Toi etc.

For the closed, centralized and popular social networks, it would probably be a good idea to allow API for sharing User.JS scripts that have a minimum rate of popularity, to avoid complains about malicious User.JS scripts.

In concern to censorship, User.JS scripts such as [IMDB Pirate d Version for Greasemonkey - Userscript s.org](http://userscripts-mirror.org/scripts/show/21977) even though ARE ABSOLUTELY LEGAL and are educational to a high level, big and biased interests would make a lot of noise out of such User.JS scripts.
We really need to be cautious about this and also be ready to be subjected to censorship, at least on the closed and centralized social networks.  It would be easier to start off with decentralized and free social networks such as diaspora*, GNU Social, Hubzilla, Movim, RedMatrix, Salut à Toi etc.

For the closed, centralized and popular social networks, it would probably be a good idea to allow API for sharing User.JS scripts that have a minimum rate of popularity.

In concern to censorship, User.JS scripts such as [IMDB Pirate d Version for Greasemonkey - Userscript s.org](http://userscripts-mirror.org/scripts/show/21977) even though ARE ABSOLUTELY LEGAL and are educational to a high level, big and biased interests would make a lot of noise out of such User.JS scripts.

**Comment by sizzlemctwizzle** [comment]
I say we have a "Share" button that prompts you to install a script, that once installed let's you share scripts on various social media sites. That way we don't have to be beholden to any TOS agreements. Users are acting of their own accord with a little client-side automation for convenience.

We could put the script on GitHub under our organization, then I'd fork it and sync it on to my OUJS account. I'd give @Martii access to my fork of course.

**Comment by Martii** [comment]
> We could put the script on GitHub under our organization, then I'd fork it and sync it on to my OUJS account.

That's a lot of work if you are willing to take that on.... you'd need to tell me which repo to maintain as primary... most likely it'll be here first then on OUJS pro.

See also:
* #231 *(organization direct)*
* #236 *(organization direct)*

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
