### ISSUE TITLE
case insensitive groups

### ISSUE THREAD

**Issue by jesus2099** [OpenUserJS/OpenUserJS.org#421]
I have just noticed that there were two github groups: [github](https://openuserjs.org/group/github) and [Github](https://openuserjs.org/group/Github).

It would be nice to either allow only lowercase groups or manage them as greatly as uso did manage tags where you could write what you want and in the end, user defined style **GitHub**, **Git hub** and **github** would all be preserved in users’ pages but the URLs would be the same **github** for all of them.

**Comment by Martii** [comment]
> user defined style GitHub, Git hub and github would all be preserved in users’ pages but the URLs would be the same github for all of them.

Only way I can think of to do this currently is if we "merge" the results of the identically named groups e.g. when searching for groups use a regular expression search query... so we would still have separate groups of different casings but invisible to the end user... as far as "Git hub" goes that would be a white-space trim of 0 and that assumes we want to do that.

> I suggest that lowercase should be used.

As far as url access +1

**Comment by Martii** [comment]
I think there might be an alternate method at [`089c106`./models/group.js#L17](https://github.com/OpenUserJs/OpenUserJS.org/blob/089c1065ce33405b749a41884f41f6ba436cccd9/models/group.js#L17) creating another property with the user defined name.

**Comment by Martii** [comment]
The following groups were merged into their oldest counterpart:

``` console
576e4763b914c2e2171159af COMPLETED 'facebook'
57ef0b30106a9b5e67232274 COMPLETED 'wikia'
54a699acceb28be15de342cc COMPLETED 'oujs'
595cfea211362b5a963b3972 COMPLETED 'hacker news'
568a5f4cd126585c0b64c8bc COMPLETED 'mediawiki'
58167c9abd6a942e1787deb8 COMPLETED 'steam'
5b48366560d93702d74268e3 COMPLETED 'wiki'
592604c40efaf64bab022c46 COMPLETED 'gitlab'
544f7d72acc4d80000a00c4a COMPLETED 'twitch'
54442099122a5b00003964f4 COMPLETED 'reddit'
593954fd59bc89690df51256 COMPLETED 'geocaching'
5b274e1b1b790c02d78f8226 COMPLETED 'youtube'
5522e6acfdf3dd2c4f476dd2 COMPLETED 'youtube'
54593a7350f5e400003b92e6 COMPLETED 'github'
5651e150b788fccf11be1d32 COMPLETED 'github'
```

... needs final check for duplicate names. 

Re:
@jerone

> There shouldn't be any difference between lowercase, uppercase and anything in between.

if `gi thub` vs `github` exists then it's probably a different tag. There are many variations on this. The end user should learn to use the tab key in *select2* to create a new/existing group. Unless you have a better idea after the final check I'll close this.

@jesus2099 

Hey... if you have some time would you please double check OUJS to make sure no groups are duped with casings. I'd appreciate it. Paralax is definitely getting to me tonight.

**Comment by Martii** [comment]
That's good news. Thank you for checking.

Closing from no further comments from parties. Leave a message here if someone sees it messing up please.
