### ISSUE TITLE
Unminify Source Code

### ISSUE THREAD

**Issue by Zren** [OpenUserJS/OpenUserJS.org#437]
New dependancy: http://jsbeautifier.org/
### Test it

Open up: https://openuserjs.org/scripts/Zren/TestMinification.min/source
Copy paste the following into the console.
First the source of this: http://jsbeautifier.org/js/lib/beautify.js
Then this:

``` javascript
ace.edit('editor').getSession().setValue(js_beautify(ace.edit('editor').getSession().getValue()));
```

**Comment by Martii** [comment]
bootstrap doesn't appear to have a multi-state button. If it becomes really necessary to do this we can bloat out our code here with another static but I still prefer to keep this user.js side as a Unit Test for Ace. Closing.
