### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by jerone** [OpenUserJs/OpenUserJS.org#450]
I want to propose that we are going to start use (and integrate) [Gitter](https://gitter.im/) for questions and development chatting.

> Gitter is built on top of GitHub and is tightly integrated with your organizations, repositories, issues and activity.

Besides unlimited public rooms, there's one private room for our organization.
When activated we also could integrate it into our repository to show the activity done the repository.
Using it is easy as it supports Markdown.

I've been using it for a while now and it works great. [Many major](https://gitter.im/explore/tags/javascript,php,ruby) open source software on Github have a public room.

Our public room is at https://gitter.im/OpenUserJs/OpenUserJS.org
Our private room is at https://gitter.im/OpenUserJs

With the chat also comes a badge.

**Comment by Martii** [comment]
@jerone 
Perhaps adding this to an "unofficial" chat zone type page on the `/about` route could be an option. Does that sound like an option to get this closed? I really don't have enough time in the day to zip over to a third party site and read even more each day.

**Comment by Zren** [comment]
It sends you emails a few hours after theres been conversations you havent read. But tbh, if the devs dont use it, then theres not much point to drawing more attention to it.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
