### ISSUE TITLE
Delete the require('controllers/users').edit controller

### ISSUE THREAD

**Issue by Zren** [OpenUserJs/OpenUserJS.org#467]
Found an abandoned controller. It still references `modelList.listScript` which was removed ages ago which first through me off. Found it while refactoring routes to `/account/`.

No reference in: https://github.com/OpenUserJs/OpenUserJS.org/blob/master/routes.js

Edit: Accidently made the PR before filling out stuff.

**Comment by Martii** [comment]
@Zren 

Do you mean this one at [controllers/user.js#L667-L744](https://github.com/OpenUserJs/OpenUserJS.org/blob/df10ef2b75d53d52a8458600d45cbd0ef7bc5ad6/controllers/user.js#L667-L744) ?

**Comment by Zren** [comment]
yes

**Comment by Martii** [comment]
> Accidently made the PR before filling out stuff.

Do a have a specific commit reference to your PR that I can cherry pick and merge into a new branch for you to get credit?

**Comment by Zren** [comment]
Don't care.

**Comment by Martii** [comment]
Thank you.
