### ISSUE TITLE
Legacy route detected for GH importing

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#468]
Recently just discovered at [http://localhost:8080/users/marti/github](http://localhost:8080/users/marti/github) ... it might be useful to list that at https://openuserjs.org/user/add/scripts or do something else with it.

**Comment by Martii** [comment]
> Also be sure to delete `libs/repoManager.js` as this controller is the only one left that references it.

Are you sure @Zren ? See [controllers/scriptStorage.js#L404](https://github.com/OpenUserJs/OpenUserJS.org/blob/3a282c66452f895cd1f70871bbb9526885753a87/controllers/scriptStorage.js#L404) from current HEAD.

**Comment by Zren** [comment]
Thats because my refactoring of that function hasnt been merged.

**Comment by Martii** [comment]
I figured that. Please don't recommend things that aren't merged. Everything should be off of the current HEAD not a PR.

**Comment by Martii** [comment]
Closing as sync on pro works. If we need a different, more up to date, landing page there open an issue for it please. Thanks for your assistance Zren.
