### ISSUE TITLE
Google OpenID Deprecation

### ISSUE THREAD

**Issue by jerone** [OpenUserJs/OpenUserJS.org#484]
More info:
* https://support.google.com/accounts/answer/6135882
* https://developers.google.com/accounts/docs/OpenID#shutdown-timetable
* https://www.npmjs.org/package/passport-google
* https://github.com/jaredhanson/passport-google/issues/25

Solutions:
* https://github.com/jaredhanson/passport-google-oauth
* https://www.npmjs.org/package/passport-google-oauth-2
* https://www.npmjs.org/package/passport-google-auth
* https://www.npmjs.org/package/passport-google-oauth2
* http://iao.fi/myposts/passport_google_openid_migration

**Comment by Martii** [comment]
Some notes out loud:

Same maintainer as our current google passport is at https://github.com/jaredhanson/passport-google-oauth with `$ npm install passport-google-oauth` from https://www.npmjs.com/package/passport-google-oauth ... seems to be a little out of date though but so is the OpenID package from this same project maintainer.

Based off observational stats only the package at https://www.npmjs.com/package/passport-google-auth appears to be the more maintained and contains an issue tracker unlike the other two forks.

This is beyond my capabilities at the moment and this should be completed relatively soon with either deprecation/eol or migration to OAuth google package. Setting to expedite.
