### ISSUE TITLE
Logging in with Github gives me a redirect loop in both Chrome and Firefox

### ISSUE THREAD

**Issue by WoLpH** [OpenUserJs/OpenUserJS.org#506]
The result is the same in both Chrome and Firefox (latest versions) and consistently repeatable.

Anyone has a clue what might be wrong?

![screen shot 2015-01-05 at 02 18 56](https://cloud.githubusercontent.com/assets/270571/5608343/4706985a-9481-11e4-85ca-9bf5914578ba.png)

**Comment by Martii** [comment]
Little more specific would help... works here in:

* Mozilla/5.0 (X11; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0 *(34.0.5 Moz Linux 64 bit build)*
* Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0 *(34.0.5 Windows 7 32 bit build)*
* Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 *(Chrome)*


> Anyone has a clue what might be wrong?

Clean profiles? Clean system? *(Try CCleaner or equivalent if Windows)*

**Comment by WoLpH** [comment]
Not really sure what specifics to give as it's a multi-browser issue. I get the same results on 2 completely separate machines.

Attempts so far:
- OS X:
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.45 Safari/537.36
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0
- Windows:
  - Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
  - Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0

It could be related to some of my browser extensions, but I can repeat the same problem over and over again with all of the above mentioned browsers.

**Comment by WoLpH** [comment]
Upon further inspection, it appears to be related to the Ghostery addon/extension. Completely disabling the extension appears to work even though Ghostery doesn't appear to be blocking anything.

One way to work around the issue is to cancel the redirect loop (i.e. `ESC`) and opening the OUJS site again. Not sure if it's a race condition or anything but it appears to work after a few seconds.

Regardless of the cause though, an infinite redirect loop seems bad for both the users and the servers, perhaps it should give up after 5 consecutive attempts?

**Comment by Martii** [comment]
> it appears to be related to the Ghostery addon/extension.
...
> Regardless of the cause though, an infinite redirect loop seems bad for both the users and the servers, perhaps it should give up after 5 consecutive attempts?

I will look into it but it is unlikely that it has anything to do with our project here at OUJS... it could be available in the *passport* package itself... labeling as invalid since your Ghostery add-on is the culprit. This isn't the first time that add-on has wreaked havoc with system. If it is found to be exclusively out of OUJS control then will followup with that. Closing with mitigation.

**Comment by WoLpH** [comment]
That's fair indeed, now it's in the search though for anyone having problems in the future :)

I'll report a bug with Ghostery as they appear to be blocking stuff without any mention of it in the logs. Unblocking everything with Ghostery is always my first step when sites behave buggy but there wasn't anything to unblock in this case...
