### ISSUE TITLE
The scripts should have a "Flagged" counter with filters and explanation

### ISSUE THREAD

**Issue by WoLpH** [OpenUserJs/OpenUserJS.org#508]
Right now the interface makes me think the counter is out of date, apparently (as explained in https://github.com/OpenUserJs/OpenUserJS.org/issues/418#issuecomment-68729574) this is due to one of the scripts being flagged.

It would be very helpful to have a separate section with flagged scripts (could be a separate table at the top of the screen as they obviously require attention). In addition, what do the flags mean? The script in question has 2 flags without any information about what a flag actually means or why it's there.

**Comment by Martii** [comment]
> Right now the interface makes me think the counter is out of date

This is agreed upon.

> In addition, what do the flags mean?

This is a second duplicate feature enhancement that may be implemented in https://github.com/OpenUserJs/OpenUserJS.org/issues/262#issuecomment-57592127

In all summary this is related to #262 and just barely goes outside of the scope of it with the counter... so leaving as an enhancement but it's part of that milestone.

**Comment by sizzlemctwizzle** [comment]
The number of flags is only shown to moderators and up to prevent hivemind flagging. Flags are only for malicious scripts and very few users are even capable of accurately detecting that kind of script. Having a section for flagged scripts out in the open would just make matters worse. We already get enough false positives. Anything else here, I've seen discussed elsewhere.

**Comment by Martii** [comment]
@sizzlemctwizzle 
I'll open a new issue a little more specific. The flag counter isn't what I was talking about. If a script is flagged then the script count is adjusted accordingly so I always have to click "Scripts" on a user profile during admin in case somethings hidden or visit the moderator tools.
