### ISSUE TITLE
14th Date Bug

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#512]
Did a search couldn't find anything on this. It seems all the listing over 6days old has it's update value set to the 14th xxxx.

See image below:

![090](https://cloud.githubusercontent.com/assets/8114076/5688001/604b3196-984a-11e4-80f5-d6d6bdbb0056.png)

**Comment by Martii** [comment]
> It seems all the listing over 6days old has it's update value set to the 14th xxxx.

It's actually approximately 9 days and that's the year e.g. `2014 == '14`. If you need to know the exact date the tooltip shows you it on hover. Marking as invalid with close.
