### ISSUE TITLE
Put "userscripts" somewhere prominent on the main page

### ISSUE THREAD

**Issue by Ede123** [OpenUserJs/OpenUserJS.org#547]
Currently if you Google for ["userscripts"](https://www.google.de/search?q=userscripts) (which is probably what you're googling for if you're looking for a userscripts repository) OpenUserJS is only listed somewhere on the second page (and even then it's a link to the [userscripts.org group](https://openuserjs.org/group/userscripts.org)).

I assume it would already be a huge bonus to include just the word "userscripts" somewhere prominently on the main page. In fact our main page currently is not only unfriendly with respect to search engine indexing but also for new potential users who don't know about OpenUserJS yet and could use at least a very brief description of the site.

If you compare with similar projects (which appear earlier in search results) all of them have some descriptive text right on their front page!

**Comment by Martii** [comment]
> "userscripts" somewhere prominently on the main page

We already have `keywords` with every page:

``` html
<meta content="userscript, userscripts, javascript, Greasemonkey, Scriptish, Tampermonkey, extension, browser" name="keywords">
```

and

``` html
<meta content="Download userscripts to enhance your browser." name="description">
```

SEO refinement may come at a later date. Having the words itself on every page is not a requirement for spidering and is usually the last thing to determine a ranking.

> but also for new potential users who don't know about OpenUserJS yet and could use at least a very brief description of the site.

https://openuserjs.org/about ... also on every page in the footer. :) Taggin a later as most of this is already implemented. I'll leave this open in case someone else has something to say but most likely it will be closed sooner than later.

**Comment by Ede123** [comment]
I didn't say on every page but on the [main page](https://openuserjs.org/)!

Also I didn't suggest any long description but just a very short (but descriptive) catchphrase, e.g. "Free userscript repository" which everybody immediately understands.


> https://openuserjs.org/about ... also on every page in the footer

Well, an about page is nice to have but
* As you say yourself it's in the footer. People are lazy. If they do not get immediately what a site is about when visiting it they'll probably leave before even scrolling down all the way.
* It's tech-talk to the average visitor. I assume most people would fell informed better by just a catchphrase like I suggested instead of a lengthy mission statement.


Do whatever you like (you're free to do so) but I definitely feel there's a lack of popularity for OpenUserJS (which is an absolutely great project, but won't be able to survive without people to bring life to it) and that there's some need to change something about it.

**Comment by Martii** [comment]
> It's tech-talk to the average visitor.

I'm sure that @JRInge would feel differently as do I. He is the main contributor for those pages along with the main owner of the project and myself.

> I didn't say on every page but on the main page!

Point is it is already on every page not just the main one.

> People are lazy.

Don't assume someones motivations. If you are lazy then that is your issue. Don't project your habits on others. Some UI interactions can be anticipated and accommodated but this isn't one of them.

> (which is an absolutely great project, but won't be able to survive without people to bring life to it)

Thank you and please don't sensationalize. Ranking is not the end of the world. We are doing just fine. Perhaps if you knew a bit more about SEO you would realize that you have a part in this as well. Link into our site on sites that allow it and that will improve the ranking according to your perception. I've done a ton of SEO management for many companies and I know exactly what should be done.

I think the most that you'll get from me in the short term is a tooltip on the main logo link in the upper left but we'll see if one of our other collaborators has anything additional to add.

**Comment by Ede123** [comment]
First of all: No reason to get personal. Impolite devs are actually a good way to drive people away, too.
Secondly: I want to help here! If you don't get that, it's not a problem for *me*

Thanks for the tooltip but I'm afraid discoverability is even worse than the About page linked in the footer.
Also note that I initially presented SEO as an issue, but I wanted to point out "human being optimization" is an issue, too. And for humans you don't have it visible "on every page"

**Comment by Martii** [comment]
> No reason to get personal.

Don't mistake directness as impolite. I am a succinct person and I most definitely don't need to justify this portion any further.

Being extremely direct here... pay attention to the TOS specifically in regards to [etiquette](https://openuserjs.org/about/Terms-of-Service#etiquette) 2nd bullet and 4th bullet *(and also applies here and referenced at [contributing](https://github.com/OpenUserJs/OpenUserJS.org/blob/master/CONTRIBUTING.md))*. You aren't giving others a chance to respond and are borderline being snarky. Please refrain from this in your future communications. OUJS doesn't need that nor should you be emanating it profusely.

SEO is near the last thing in my priorities but it may not be in others. Your phobia is noted which is why this issue is still open. Anyhow this tangent you've decided to traverse is off topic. Further responses in that regard will merit closure of this issue.

As a rule of thumb Jesse from USO has the optimum domain name and so does the mirror backup... so they will always rank higher due to that fact alone. You also failed to search for preexisting issues in which I re-noted one above directly related to this one.

> I want to help here!

That's great that you have a common goal. Keep in mind that you aren't the only one. Screen real estate is always a factor and putting a lot of what you think might improve our ranking needs to be evaluated by others. I would suggest re-reading the CONTRIBUTING.md and the all the links therein first.

**Comment by Ede123** [comment]
> Don't mistake directness as impolite or personal. I am a succinct and mostly a literal person

Yeah, in your imagination maybe... (Or you have a twisted definition of those words.)

> SEO is near the last thing in my priorities but it may not be in others. Your phobia is noted which is why this issue is still open. Anyhow this tangent you've decided to traverse is off topic. Further responses in that regard will merit closure of this issue.

The only phobia I see here is you obsessing with (or rather obsessing with not doing) SEO. My argument to give a visible and succinct description of the page for the good of human beings was - again - ignored.

If you're lecturing me with the etiquette go on and read it yourself,  too (it applies to your answers at least as much as to mine). And if you want to close this topic now go on with it. I'm certainly not obsessed with it and can live well with USO going it's own (your) way, especially since there are more than enough alternatives right now (and then again that was exactly what I was trying to tell you from the beginning but about which you seem to be in denial about).

**Comment by Martii** [comment]
Last warning for violating the TOS. This issue is closed. You failed to give anyone else a chance to respond and possibly take on this isssue. You also have way too much "Passive aggressive behavior with abrasive commenting". One more instance and your account will be removed. Thanks and cheers. :)
