### ISSUE TITLE
Update copyright to 2015

### ISSUE THREAD

**Issue by sebie** [OpenUserJs/OpenUserJS.org#578]
>Tags relevant: `UI`, `enhancement`

The title is self-explanatory. 

The copyright text on the bottom left corner *should* be updated to 2015.

**Comment by Martii** [comment]
Thanks but the standard for Copyright is the year a work is created/published and the plus *(+)* symbol is perpetual. For additional information feel free to visit http://www.copyright.gov/help/faq/
