### ISSUE TITLE
Security issue with redirect url

### ISSUE THREAD

**Issue by jerone** [OpenUserJs/OpenUserJS.org#609]
https://github.com/OpenUserJs/OpenUserJS.org/commit/d2a8b629e6bd6eff21a2ffeb9d8ef0639f6b2bf5#commitcomment-10437728

> This change creates a **big security issue**. One from the [OWASP top 10 violation](https://www.owasp.org/index.php/Top_10_2013-Top_10): [OWASP A10 - Unvalidated Redirect](https://www.owasp.org/index.php/Top_10_2013-A10-Unvalidated_Redirects_and_Forwards). 
> 
> You publicly store the redirect url without validating it, which is valuable for phishing and spam. The session redirect wasn't perfect too without validation, but at least it was hidden from the public.

**Comment by sizzlemctwizzle** [comment]
I knew I forgot to do something. Nice catch.

**Comment by Martii** [comment]
This feature should probably default to `.../` when authentication changes to guest e.g. when I log out and I'm on an admin page it "gracefully fails" which mucks up the logs a bit.

**Comment by Martii** [comment]
Redirect loop detected... log in with an account that doesn't exist to have it redirect back to `/register`... then login with one that does and redirect takes it back to `/register` ... auth routine okay but redirect validation needed.

**Comment by Martii** [comment]
@sizzlemctwizzle and/or @jerone 
Is there some reason why `getRedirect()` is in two places *([here](https://github.com/OpenUserJs/OpenUserJS.org/blob/b300317930394b5679df2b7e0acfdb4c95aee696/controllers/auth.js#L45) and [here](https://github.com/OpenUserJs/OpenUserJS.org/blob/d2a8b629e6bd6eff21a2ffeb9d8ef0639f6b2bf5/controllers/index.js#L156))* and is exactly the same code? Would it be prudent to place it in `./libs/helpers.js` or somewhere more common for reuse?

I do see the `hostname` check in these but no domain validation either. I'm thinking we are missing both near and far tampering too.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
