### ISSUE TITLE
Passport Google Dep Update Failure

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#613]
Local pro login *(after callback)* via google in the console...

``` sh-session
InternalOAuthError: failed to fetch user profile (status: 403 data: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",
    "extendedHelp": "https://console.developers.google.com"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration."
 }
}
)
    at /home/user/repo/git/oujs/martii/OpenUserJS.org/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:88:28
    at passBackControl (/home/user/repo/git/oujs/martii/OpenUserJS.org/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
    at IncomingMessage.<anonymous> (/home/user/repo/git/oujs/martii/OpenUserJS.org/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```

As I don't have access to the root OUJS google account, this needs to be handled by @sizzlemctwizzle directly for dep update *passport-google-oauth* v0.2.0 at [/package.json#L40](https://github.com/OpenUserJs/OpenUserJS.org/blob/edb8bf25c7ee3cfbffffdd87913194503494f41f/package.json#L40)

I would recommend doing this *(adding Google+ API to the OUJS google account)* ASAP in case this affects the google authentication deprecation from #484 before April 20th to avoid potential service disruption for those user accounts.

**Comment by Martii** [comment]
See also example update at https://github.com/jaredhanson/passport-google-oauth/commit/287d53b980d1c0b11d84e82caf7ab2b9c0214b17 for additional scope update.

**Comment by sizzlemctwizzle** [comment]
Just tested in on production and authentication works. Of course it doesn't work locally. We don't have OAuth creds in the development database. Even GitHub authentication would work in production locally because the callback is openuserjs.org not localhost:8080.

**Comment by Martii** [comment]
@sizzlemctwizzle 
Before you close this... **local production** which has OAuth credentials failed... did you publish to remote production e.g. nodejitsu the change? It would appear that you didn't update GH development either... reopening and reassigning.

**Comment by Martii** [comment]
P.S. I can bump the dev dep Sunday evening but if it kills nodejitsu logging in with Google it will be soley your responsibility to fix this.

**Comment by sizzlemctwizzle** [comment]
@Martii

I'm really confused. I never made any recent change. Logging in with Google OAuth on production and local production (with that callback hack you showed me) works (see user [test2](https://openuserjs.org/users/test2)). Using my main account, GitHub OAuth works on dev, pro, and local pro.

So overall I'm not sure where you're encountering a problem. Could you let me know what accounts you are using to test Google OAuth? That way I can inspect the session data. Also are you using direct login, registration, or adding a Google strategy while logged in?

**Comment by Martii** [comment]
@sizzlemctwizzle 

> Using my main account, GitHub OAuth works on dev, pro, and local pro.

Correct because the **GH Oauth** is present for all environments both in the server and user side *(hence the server side "GitHub Authenticated" message in the console we all see in dev and pro via jitsu package)*... but not all authentications are available in the dev environment user side... which is why you initially closed this issue thinking that I was in that environment and I'm not testing there. I can't test **Google OAuth** in dev without posting a key pair of my own in the API section for a little bit **or** exposing pro's credentials...which I won't do obviously for security reasons on the latter.

> Could you let me know what accounts you are using to test Google OAuth?

[Martii](https://openuserjs.org/users/Martii). You can't use AuthAs so you would need to know my pass for google.

> Also are you using direct login, registration, or adding a Google strategy while logged in?

Everything **but** new account registration, since I already have that static test account, for google. I converted my Google gmail account to Google+... current version of *passport-google-oauth* works with either account type at google... but plain google accounts are being deprecated as mentioned [above](https://github.com/OpenUserJs/OpenUserJS.org/issues/613#issuecomment-88210809) in the commit summary given at that link. e.g. the "profile" scope is being deprecated in favor of the Google+ API scope... which means the OUJS account you signed up with for the API key pairing *(Similar to the one I sent you screen shots to [developer.google.com](https://developer.google.com))* you need to add/convert that account, which you have access to and I do not, to use the Google+ API instead of their deprecated standard/classic API for any authentication... e.g. somewhere in that mess on their dev you have to add the Google+ API in order for the *passport-google-oauth* dep to be updated before they retire/EOL the standard/class API... 

If you don't do this and I *(or you)* bump the dep version it produces the the initial issue session [log reported above](https://github.com/OpenUserJs/OpenUserJS.org/issues/613#issue-65522612) and fails to authenticate at all because it has migrated to Google+ API in *passport-google-oauth* dep in 0.2.0... doesn't seem to crash "the server locally with pro credentials" *(hence local production for short)*... but one can **never* login with google to local production with a google account... and **should** be nearly the same on remote production *(or actual production if you wish to call it that)*... the only difference is node.js version here vs nodejitsu and the core platform on nodejitsu is SunOS *(Solaris)* whereas my main machine is IA64 bit *(and IntelArchitecture32 bit on another slower machine for platform testing packages out... so far I haven't encountered any difference in IA32 and IA64 but I test less periodically on it)*

Also if I correct the scope to use Google+ API **which will also have to happen at some point**... it still reproduces the Access error/exception. The dep appears okay but the credentials on remote production and local production bomb out because the OUJS account you use as the "site account" isn't configured to handle Google+ API... 

Does this make more sense?

**Comment by sizzlemctwizzle** [comment]
I just enabled the Google+ API. I also added Google OAuth creds to the dev database.

**Comment by Martii** [comment]
Hmmm not getting the issue on dev with those credentials but am getting it on my version of local pro... guess I'll just have to take a gamble on if remote pro handles it... will deploy in a few minutes... if failure that can mean one of two things... the Google+ API hasn't been enabled for production (remote pro) account or it just doesn't like it on local pro.

**Comment by Martii** [comment]
Error on remote pro *(production)* proper with [v0.1.7-53](https://github.com/OpenUserJs/OpenUserJS.org/releases/tag/v0.1.7-53).

Will attach screenshot of browser window after rollback to [v0.1.7-51](https://github.com/OpenUserJs/OpenUserJS.org/releases/tag/v0.1.7-51) but here's the *jitsu* log for my attempt at logging in with my google account on production *(dev worked fine and it prompted me for profile access as if it was brand new)*:

``` sh-session
[04/06 03:32:34 MDT][out] GitHub client authenticated
[04/06 03:35:02 MDT][err] InternalOAuthError: failed to fetch user profile (status: 403 data: {
[04/06 03:35:02 MDT][err]  "error": {
[04/06 03:35:02 MDT][err]   "errors": [
[04/06 03:35:02 MDT][err]    {
[04/06 03:35:02 MDT][err]     "domain": "usageLimits",
[04/06 03:35:02 MDT][err]     "reason": "accessNotConfigured",
[04/06 03:35:02 MDT][err]     "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",
[04/06 03:35:02 MDT][err]     "extendedHelp": "https://console.developers.google.com"
[04/06 03:35:02 MDT][err]    }
[04/06 03:35:02 MDT][err]   ],
[04/06 03:35:02 MDT][err]   "code": 403,
[04/06 03:35:02 MDT][err]   "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration."
[04/06 03:35:02 MDT][err]  }
[04/06 03:35:02 MDT][err] }
[04/06 03:35:02 MDT][err] )
[04/06 03:35:02 MDT][err]     at /opt/run/snapshot/package/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:88:28
[04/06 03:35:02 MDT][err]     at passBackControl (/opt/run/snapshot/package/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
[04/06 03:35:02 MDT][err]     at IncomingMessage.<anonymous> (/opt/run/snapshot/package/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
[04/06 03:35:02 MDT][err]     at IncomingMessage.emit (events.js:117:20)
[04/06 03:35:02 MDT][err]     at _stream_readable.js:943:16
[04/06 03:35:02 MDT][err]     at process._tickDomainCallback (node.js:463:13)
```

**Comment by Martii** [comment]
Rolled back snapshot to [v0.1.7-51](https://github.com/OpenUserJs/OpenUserJS.org/releases/tag/v0.1.7-51).

> I just enabled the Google+ API.

For both OUJS accounts in relation to their respective API keys?

**Comment by Martii** [comment]
Account corrected... thank you... assigning to me for the moment for the remainder *(with any luck)*. Will attempt the scope update in about a day of user trials after some retesting in dev.
