### ISSUE TITLE
Add "All" filter to an Issues section of a Script (and make it default)

### ISSUE THREAD

**Issue by Dexmaster** [OpenUserJs/OpenUserJS.org#615]
I suggest adding "All" option to "open/closed" in the right block of Issues section, because now by default the see only open ones.

I also suggesting making it a default one, so users would see all related Issues to a script and don't open new ones on already closed subjects.

**Comment by sizzlemctwizzle** [comment]
+ 1 for both suggestions, except open issues is the default for the user than owns the script.

**Comment by Martii** [comment]
+1 with @sizzlemctwizzle modification.
