### ISSUE TITLE
"Preview" button when replying to discussions should change its label to "Edit" once the preview is shown

### ISSUE THREAD

**Issue by Ede123** [OpenUserJs/OpenUserJS.org#618]
Currently the "Preview" button is also used to get back to editing mod again after previewing a post.

This is confusing at first. The button should change it's label to e.g. "Edit" as soon as the review is shown, so its functionality is accurately reflected.

**Comment by Martii** [comment]
Thanks for your input. Firstly I'd like to point out that the text is generated by the [*bootstrap-markdown*](https://github.com/toopay/bootstrap-markdown/issues) package. Secondly *bootstrap* itself has a slight color tint change stating that it is in preview mode. e.g. all buttons in *bootstrap* are all like that. If your viewport display has poor color spacing/balancing you won't see much difference.

So based off this issues request it is an upstream issue not OUJS. It is possible to widen the color differentiation of the active buttons though on our end. Feel free to search then ask that project though.

**Comment by Ede123** [comment]
I searched the issue for you and commented that this is also problematic for OUJS. Not really my job though...
