### ISSUE TITLE
Source Code update failed

### ISSUE THREAD

**Issue by Quackmaster** [OpenUserJs/OpenUserJS.org#633]
It seems that there's something wrong with the Github Webhook.
I updated my script on Github but OpenUserJS didn't get the new source code of the script (although the version on the about page was updated succesfully).

Here is the link to my script:
http://openuserjs.org/scripts/Quackmaster/Quack_Toolsammlung

Version on the about page: 2.52.00
Version in the source code: 2.51.00

**Comment by Martii** [comment]
May have lost connection to S3 or a GH hiccup... working right now with:

* https://openuserjs.org/scripts/Marti/oujs_-_Meta_View vs. https://openuserjs.org/scripts/Marti/oujs_-_Meta_View/source with above commit ref.

Try resyncing the script or resending the request via GH.

**Comment by Martii** [comment]
Hmmm @sizzlemctwizzle are you test deploying something? Production deployment doesn't match my last release from here on dev.

**Comment by Quackmaster** [comment]
I just uploaded a new version and this time it worked - thanks Martii!

**Comment by sizzlemctwizzle** [comment]
No I just couldn't remember how to restart at the time, so I redeployed.

**Comment by Martii** [comment]
I think I'm 98% sure this is a loss in connection with S3, just like *fakes3* and 1% with a GH hiccup ... and with a bunch of restarts I haven't seen this appear again yet. Please reopen if needed. Thanks.
