### ISSUE TITLE
Delete please. I wanted the GreasyFork issues

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#639]
Please delete this. Without thinking I posted this in OUJS when I wanted GreasyFork feedback.

**Comment by sizzlemctwizzle** [comment]
First off, if you deleted a script, it's gone for good. We store nothing in
this case. If a script was removed via moderation we can retrieve
everything about it. I probably wouldn't be willing to give you the source
of these moderator removed scripts.

**Comment by TimidScript** [comment]
Posted this in the wrong place. I thought I updated fast enough guess not.

**Comment by sizzlemctwizzle** [comment]
I don't see a way to delete, so closing.
