### ISSUE TITLE
Firefox Accounts webhook

### ISSUE THREAD

**Issue by jerone** [OpenUserJs/OpenUserJS.org#64]
When Greasemonkey integrates Firefox Accounts as their sync service, make a connection with that to import all synced scripts.

https://blog.mozilla.org/blog/2014/02/07/introducing-mozilla-firefox-accounts/
https://wiki.mozilla.org/Identity/Firefox_Accounts

**Comment by Martii** [comment]
We should be reluctant to support any Mozilla based technologies at this time due to https://github.com/OpenUserJs/OpenUserJS.org/issues/358#issuecomment-170999188 *(base ref #870)* ... moving to might fix.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
