### ISSUE TITLE
Unable to change style colors

### ISSUE THREAD

**Issue by bordot** [OpenUserJs/OpenUserJS.org#653]
Hello,

I am currently trying out a local version of this script and I've been trying to make some modifications to the template via the CSS files in public/css, but no changes ever make their way to the site. I was curious if you might have a quick guide on how to make  visual changes to the site? Thanks!

**Comment by Martii** [comment]
> local version of this script

This isn't a script it's a project. :)

> how to make visual changes to the site?

Through a user.js or something you are considering contributing to the core project?
