### ISSUE TITLE
Script Name Casing Duplicates

### ISSUE THREAD

**Issue by TimidScript** [OpenUserJs/OpenUserJS.org#656]
If you change the casing of your script name you are unable to access latest version.

Steps I took and the bug it created.

I had a script name with the word "deviantART" I changed it to "DeviantArt" and updated the version from 1.0.5 to 1.0.6. In the script listing the name remains "deviantArt", but the version is 1.0.6. When you try and install or look the code, it points to 1.0.5. I fixed it by updating the script again but with the old casing "deviantArt". There might be a script floating around in the database with the name "DeviantArt", that's not deleted. 

(Making the user and script name as the UID causes some painful limitations to the script author. On top breaking auto-update, the install counter resets.)

**Comment by Martii** [comment]
This is more or less a duplicate but important enough to keep tracking as an individual issue as a watch point with the parent milestone. Thanks for the report.

**Comment by sizzlemctwizzle** [comment]
We identify scripts by @name and @namespace, which are both case-sensitive.
You created a new script when you changed the name. Even Greasemonkey would
have recognized it as a different script with the name change.

**Comment by sizzlemctwizzle** [comment]
However this bug might be the result of case-insensitivity in the actual
URL.

**Comment by Martii** [comment]
> which are both case-sensitive

Yup... and when we move to `_id` we'll need to watch that someone doesn't completely change the `@name` to something totally different but still have it access via the old `@name`, etc. URL but have GM install it under the new `@name`.

Honestly I'd rather just like to have a comparison of old to new and create a new indexed script... and if the toLowerCase of the url matches then possibly prompt.  The basic moral here is don't change the core UserScript metadata items... will be a bit tricky to handle the logic but I think it's quantifiable since we do this for discussions already.

**Comment by TimidScript** [comment]
> Even Greasemonkey would have recognized it as a different script with the name change.

GM keeps the same local storage name if you download from same place, no matter what changes you make to the meta. Old USO, GreasyFork, Gist and Github have same unquie id. All the sites you can rename and still have a unique id to keep track of the original.

Anyway, I renamed the script without much thought. I forgot about OUJS unique behaviour.

**Comment by Martii** [comment]
> If you change the casing of your script name you are unable to access latest version.

Type checks for re-casing test:
* Existing script edit - **UNCONFIRMED ISSUE** ... change `@name` and any changes in entire script are omitted
* Write script online - **UNCONFIRMED ISSUE**
* Upload script - *pending*
* Sync - *pending*

**Comment by TimidScript** [comment]
FYI: GM is case-insensitive.

**Comment by Martii** [comment]
> FYI: GM is case-insensitive.

FYI: It shouldn't be... it should be case sensitive and is reconfirmed here. 

```
Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 SeaMonkey/2.33.1
Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
```

Invalid for that portion of this report.

**Comment by TimidScript** [comment]
Odd, retested it and you are right. First time I time I tested it, I had a script called "TEST" and "test" and one overwrote the other. Tried again and not the case.

**Comment by Martii** [comment]
@sizzlemctwizzle 
Misc. note:
* Base issue where this was "corrected" was found being referenced in #130 ... with commit https://github.com/OpenUserJs/OpenUserJS.org/commit/5b65abdf577ead2472c5a5e3d455c0b77e45b089
* Period of time reminder is when you fixed my "marti" to "Marti" username access in the URI... e.g. case insensitivity on Usernames... but the `installSlugName` is completely case insensitive now which includes the Scriptnames... which is a cause for this issue. There may be more... but this is where I got a trial and error hit with seeing the missing scripts... which led me to the referenced issue list item and eventual commit.

**Comment by Martii** [comment]
@TimidScript 
You should be able to change your casing now... it will by design spawn a new script on OUJS as @sizzlemctwizzle mentioned. Let me know how it goes.

My production Unit Tests are [here](https://openuserjs.org/scripts/Marti/RFC_2606%C2%A73_-_hello,_World!) and [HERE](https://openuserjs.org/scripts/Marti/RFC_2606%C2%A73_-_Hello,_World!)

**Comment by TimidScript** [comment]
@Martii 
Thank you. Just tested it and it seems to work. I won't be renaming anything, as it will produce a new link for the homepage and all stats will be lost.
