### ISSUE TITLE
Consider modifying `.../scriptStorage.js` in `sendMeta` to send JSON

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#718]
As I mentioned [here](/OpenUserJs/OpenUserJS.org/issues/285#issuecomment-126409810):

> If there is time and if possible... I'd like to create another issue ticket with sharing a *(specific)* JSON of this data

> e.g. 
> * https://openuserjs.org/meta/Marti/oujs_-_Meta_View.meta.js would optionally return just the barebones for updating in text... or just do it all like it is doing now
> * https://openuserjs.org/meta/Marti/oujs_-_Meta_View.meta.json would return the object in JSON format

> ---

> May be useful if shared in cooperation with #77 and of course .user.js scripts.

This is relatively simple to do as our meta blocks are already an object so `JSON.stringify` could be used... does currently show in reverse order but with Objects there is never a guaranteed order as we all should know.

This could be useful for some .user.js as well.

**Comment by Martii** [comment]
Any reason why we shouldn't do something like this or alternate methodology in the code?

**Comment by sizzlemctwizzle** [comment]
You have my support on adding the `.meta.json` route. I'd leave the text version we generate as-is for now.

**Comment by Martii** [comment]
> I'd leave the text version we generate as-is for now.

Giving others migration time is probably a good thing. :)
