### ISSUE TITLE
'this that library function' is not defined.

### ISSUE THREAD

**Issue by jesus2099** [OpenUserJs/OpenUserJS.org#720]
Source code pages ([example](https://openuserjs.org/scripts/jesus2099/mb._ELEPHANT_EDITOR/source)) say : 

> 'this that function' is not defined.

But those are defined in a library scripts (see `@require` in metadata block).
I have just started using library, thus I have just noticed that.

Would it be possible or not that the error spotting tool would first parse libraries ?

**Comment by Martii** [comment]
In short there's not much we can do with *ace-builds* usage of JSHint at this time... as I mentioned elsewhere it's advisory only. With the GM API it may show inaccurate messages as well... luckily it's just a small triangle in the gutter. :)

> Would it be possible or not that the error spotting tool would first parse libraries ?

The editor only parses the current document and not all associated documents... nor do I think it would be wise to pull all the external sources automatically.

Historical refs:
* https://groups.google.com/forum/#!msg/ace-discuss/c7iUq--9r_k/LAz6aCwpk9MJ
* https://github.com/ajaxorg/ace-builds/issues/47#issuecomment-62278088

Thanks for the notification/suggestion though.

**Comment by jesus2099** [comment]
No problem, I just asked in case it was an oversight.
Thank you for this information, keep up the good work ! :)
