### ISSUE TITLE
Libraries don't appear to sync

### ISSUE THREAD

**Issue by Martii** [OpenUserJS/OpenUserJS.org#723]
Apparently this seems to go [way back in the initial commit](https://github.com/OpenUserJs/OpenUserJS.org/commit/f6da2c3b6ffa78b5dd150455cd12c206fea1ceaa#diff-b755ddbc6b2edf964c5586d742e3afdaR179)... _(pre me being here)_ ... and propagated ever since through refactors of GH importing.

Option 1: Sync any `*.js` and `*.user.js`

Option 2: Modify the sync script column at https://openuserjs.org/user/add/lib ... to reflect what we don't do.

Option number **one** is preferred imo.

---

Historical issue(s):
- #2

**Comment by Martii** [comment]
We could use the OpenUserJS metadata block and a new key to detect these btw... just a misc. thought. Will need to parse the full compliment of parsers though *(which is relatively easy as I started out doing that)* as I only parsed the UserScript metadata block in #724

**Comment by sizzlemctwizzle** [comment]
I really like that idea. It gives us a way to get the name, version, and
license from the library source.
