### ISSUE TITLE
Modify `.../scriptStorage.js` in `sendMeta` to trim up .meta.js route text to barebone keys/blocks

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#725]
@sizzlemctwizzle [wrote](/OpenUserJs/OpenUserJS.org/issues/718#issuecomment-135142897):
> Although trimming it down in the future to `@name`, `@namespace`, `@version` should be a goal.

Followup from #718 

Let's give some time to migrate any scripts that may need/want to use the JSON route **and** some time to weigh in on this. *(adding needs discussion to this during this waiting time... I'm at +1 __unless otherwise convinced__... and I can presume @sizzlemctwizzle is at +1 by his statement)*

Loosely related to:
* #77

**Comment by Martii** [comment]
@elundmark
We could use your expertise here on why you are inserting some unique keys in that don't pertain to sizzles suggested values. Doesn't mean you have to use it but would be grateful for your input on this issue. TIA. :)

**Comment by elundmark** [comment]
@Martii - You must have the wrong name, or am I going senile? :-)

**Comment by Martii** [comment]
LOL You aren't going senile... was curious about some of your "rolled meta" values that you put into your consolidation of `@updateURL` versus what OpenUserJS.org *(OUJS)* offers now and what this issue is going to offer in the meta.js routine. The meta.json routine should always have everything we collect but trimming up the "fat" so to speak for all the .user.js engines is a goal with this issue. :)

**Comment by elundmark** [comment]
Sorry, am I missing something here? I don't remember ever contributing to this project, which is confusing the hell out of me.

But since I just yesterday edited that very meta key in a couple of my userscripts, are you asking me why I write `@updateURL` and `@downloadURL`  like this?

```
// @updateURL     http://f.3r1k.se/js/tz-aio/tz-aio.meta.js
// @downloadURL   http://f.3r1k.se/js/tz-aio/tz-aio.user.js
```

I can't see what is so unusual about it?

My bad if I'm acting weird or anything, it just that:
* English isn't my first language
* I live "off the grid" plus I rarely if ever interact with anyone on the net.
* My knowledge in programming is pretty much limited to javascript.

**Comment by Martii** [comment]
> am I missing something here?

I am asking for your input/feedback on why you add certain keys to your .meta.js file such as the one you mentioned at http://f.3r1k.se/js/tz-aio/tz-aio.meta.js with:

``` javascript
// ==UserScript==
// @name          Torrentz All-in-One
// @version       2.9.8
// @date          2015-09-28
// @namespace     http://elundmark.se/code/tz-aio/
// @homepage      https://github.com/elundmark/tz-aio-userscript
// @downloadURL   http://f.3r1k.se/js/tz-aio/tz-aio.user.js
// @updateURL   http://f.3r1k.se/js/tz-aio/tz-aio.meta.js
// ==/UserScript==
```

To more precisely ask the question... why did you choose to include `@date`, `@homepage`, `@downloadURL`, `@updateURL` in your **meta.js** file? Do some user script engines require those? This issue ticket is to trim down the excess from the meta routine we offer directly at OUJS.

> I don't remember ever contributing to this project

We've all been watching everyone for how they do things perhaps to incorporate some improvements into the site. I thought with your expertise you could at least comment on what you might want to see. :)

> English isn't my first language

C++ is my first language. ;)... there are always translators if you feel more comfortable reading those.

> I can't see what is so unusual about it?

Don't worry... we aren't as paranoid as other sites as you may have recently encountered elsewhere but we are still cautious with consolidation... but that isn't the point of me asking you here. I just thought you might enjoy sharing your advice. :) Contributions don't necessarily entail Code but can include methodology.
