### ISSUE TITLE
Server down/stalled...

### ISSUE THREAD

**Issue by Martii** [OpenUserJs/OpenUserJS.org#944]
I'm unable to get into the VPS to restart it and it's spinning in a web browser. **NOTE**: This is purely a VPS issue with our provider and not the project nor the *node* configuration.

Messaged @sizzlemctwizzle Cc: @jonleibowitz

---

Last script update on local pro at 2016-04-05T12:07:05.214Z

Refs:
* https://openuserjs.org/discuss/Huge_Number_of_Downloads *(general issue on pro)*
* https://openuserjs.org/announcements/Server_Maintenance#comment-153ed665673 *(announcement on pro)*
* https://status.github.com/messages *(May be related to queue backlog and other GH related issues today... ongoing so far... slightly affecting local pro)*
* http://forums.debian.net/viewtopic.php?f=17&t=127845 *(not exactly what happened this morning but possible if it's indexing constantly... allegedly another dist-upgrade should fix according to this)*
* http://forums.debian.net/viewtopic.php?f=5&t=127832 *(kernel update breaking things... this is my guess)*
* https://www.debian.org/News/2016/20160402 *(latest intel on fixes)*
* #425
* Tampermonkeys derived code with `q.XMLHTTPREQUEST.RETRIES` in .user.js

**Comment by Martii** [comment]
Found a break in the system either a hiccup on whatever is causing this... or my distro update on laptop which may have a compatible client to connect to the latest Debian... although I did try Windows too and that failed... so not entirely sure.

I have already seen a 503 with *toobusy-js* on login that is probably GH's issue... leaving this open for a more detailed investigation over the next few days. Apologies for this unscheduled outage.

Btw dist-upgrade yielded no further updates. :\

**Comment by Martii** [comment]
Looks like it's still down... on laptop here.

**Comment by Martii** [comment]
No word yet.

**Comment by Martii** [comment]
PENDING!... got 5 "too busy's" on login... but I have now have access... we'll see how long this stays up on the VPS.

**Comment by Martii** [comment]
One server restart detected... investigating.

**Comment by baivong** [comment]
503 ...

**Comment by Martii** [comment]
I know... it's going to take a bit to resolve this... something is chewing up memory and causing the VPS to crash... this was before the 503 addition of *toobusy-js*... I'm probably going to take the server down, do some recompilations, and see if that helps. e.g. why it's PENDING status right now.

Patience please. :)

**Comment by Martii** [comment]
Downgrading *node* didn't help... seems that the malloc *(or whichever lib is being used)* isn't freeing up memory in the distro/VPS.

I'm going to try disabling minification just to be sure... with an environment variable to be added.

**Comment by Martii** [comment]
Still losing memory, although slower, with disabling of script minification... e.g. the VPS is going to crash again... watching it right now go down, down, up, down, down, down, up, down, down, down, etc... until eventually there is zero free memory.

So systematically ruled out our project and reaffirmed this is a distro/VPS issue. :\

**Comment by Martii** [comment]
And there it goes. :\

**Comment by Martii** [comment]
Have to AFK for a few hours... will be back to try some other things. :\

**Comment by Martii** [comment]
@sizzlemctwizzle  and anyone watching,
So I've put up a constant 503 on all routes at the moment... it's not very pretty but it will at least let everyone know that "we're busy... try again later". This is hard-coded into the app.js with `FORCE_BUSY=true` in the `env` and not here on GH dev yet... still running some tests to see if this portion stays up. So far we are around a constant ~6% memory usage... will monitor this for a few hours... sleep in between... waking up... seeing if Debian has an update that fixes this before I report it, etc.

I've tried many different versions of *node* all result in the same issue with this kernel image on  the VPS.. e.g. memory gets eaten up. Using the precompiled *node*s, the server lasts for less than 5 minutes... with a manual build from *node*s source I can sometimes get about 45 minutes of uptime. **NEITHER OPTION IS SUITABLE** as I can't babysit the server that constantly.

I've also tried to backout/rollback the last dist-upgrade and of course the old packages aren't available on the official repos... so that will fail.

Only three options are left that I can think of... 

1. Run the kernel recovery, assuming this works, and see if that works. There is exactly one snapshot, and only one, of this bad VM... so twiddling can be undone now.
2. Recreate the VM from scratch and see if it still does this memory leak... if it does switch distros in the VM. Some of this is beyond my access as well as @sizzlemctwizzle did some configuration that I'm not aware of *(yet?)*
3. Wait......................... *(as for this option... adding tracking upstream... I'll have to create an issue on Debian first, then nodejs)*

**Comment by Martii** [comment]
~6.5% memory usage with styling applied to 503's

Manually enabling /about routes to test stability

**Comment by Martii** [comment]
~15% peak memory usage with /about routes ... no leaks detected

Manually enabling /users route to test stability

**Comment by Martii** [comment]
~7.1% nominal and ~8.6% peak memory usage with /users route ... slightly slower to release memory on /users/*username*/comments

Manually enabling /forum route to test stability

**Comment by Martii** [comment]
~6.4% nominal and 7.4% peak memory usage with /forum route

Manually enabling all other discussions

**Comment by Martii** [comment]
~7.1% nominal and ~8.8% peak memory usage for global discussions

Manually enabling /group route excluding api search to test stability

**Comment by Martii** [comment]
~7.5% nominal and 8.9% peak memory usage for /groups route

Manually enabling /libs route excluding general / route ... this doesn't include script installations just yet but does show Source Code tab ... to test stability

**Comment by Martii** [comment]
~7.5% nominal and ~7.7% peak memory usage for /libs route

Manually enabling /scripts route excluding general / route ... this also doesn't include script installations but does show Source Code tab... to test stability

**Comment by Martii** [comment]
~9.3% nominal and ~14% peak *(spiked)* with average ~9.5% peak memory usage

Manually enabling /meta route to test stability

**Comment by Martii** [comment]
~9.8% nominal and ~16.7% peak *(spiked)* with average 10% peak memory usage ... fast to release on spikes and nominal

Manually enabling /install and /src routes ... we are in READ ONLY mode right now for script sources e.g. no editing... presuming anyone is still sessioned... Minification of script source is also skipped.

**Comment by Martii** [comment]
Disabling [prior routes](https://github.com/OpenUserJs/OpenUserJS.org/issues/944#issuecomment-207104199)... CPU leak detected as well... this wasn't happening before the distro upgrade so it shouldn't be us but at least I know where to look in depth.

~20% nominal and ~41% peak... loses stability after about 0.75 hours.

**Comment by Martii** [comment]
Manually enabling / route

**Comment by Martii** [comment]
Renabled /meta , /install and /src routes for testing alternate script serving method instead of `res.pipe` method... memory consumption has dropped to 13% on initial start... CPU is still a little high still though... this might be promising.

**Comment by Martii** [comment]
Creeping up again... and CPU is sometimes **above 100%** which doesn't make much sense to me.

**Comment by Martii** [comment]
\> 60% memory usage

**Comment by Martii** [comment]
I know this is against STYLEGUIDE.md but manually trying ES6 `let` in this area... restarted server.

**Comment by Martii** [comment]
Nominal around 34-35%

**Comment by Martii** [comment]
Temporarily reenable all routes *(e.g. you can log in and do as usual before this issue)*... if this crashes again I'm pretty much left with disabling the /install and /src routes... /meta should be okay since I trimmed that up in a prior issue a while back.

**Comment by JasonBarnabe** [comment]
Traffic to Greasy Fork has increased 10-fold over the past couple days, with Chrome script update checks going from 10% of traffic to 90%. I imagine this may be the thing affecting you as well.

**Comment by Martii** [comment]
Yah I checked your site as well and got a too busy a few times... I'm hoping that TamperMonkey is still caching `@requires`... that was an issue back in the USO days. Thanks for the heads up.

**Comment by Martii** [comment]
Server died again... was doing well between 40-52% ... restarted.

**Comment by Martii** [comment]
Died again... setting lag to 60

**Comment by Martii** [comment]
I'm probably going to move the git master/branch to the /admin route so it is explicitly called and doesn't accidentally trip the server by a visit to /about ... I've done that a few times during heavy traffic loads myself since inception and there's little error protection in that package *(even though there should be)*.

**Comment by TimidScript** [comment]
[Now I understand the influx](https://openuserjs.org/discuss/Huge_Number_of_Downloads).

**Comment by Martii** [comment]
Here's a 7 day current activity graph on what I've been dealing with combating:

![activity](https://cloud.githubusercontent.com/assets/114709/14402157/9fd8f58c-fde8-11e5-8d0d-317e43d3a53c.png)

Notice April 5th is when the shiz hit the fan... that's when at least 3 events happened and is dragging the server under.

I appreciate everyones patience on this and eventually things should get better.

**Comment by Martii** [comment]
So this is a snapshot of the duration when I cut off all scripts that didn't have an appropriate `@uploadURL` as well as the 9 scripts that I added one to:

![postactivity](https://cloud.githubusercontent.com/assets/114709/14402587/c819ab7c-fdf7-11e5-96fa-fcecd5cd7345.png)

... the red arrow is roughly when I cut off those scripts.... we've returned somewhat to nominal.

**Comment by derjanb** [comment]
@Martii I'm so sorry. It seems that under certain conditions (which in theory never should occur) the update check runs into an endless loop. Affected people should be able to work-around the issue by setting the "Script Update" -> "Check Interval" option to any other value than "Never".

I'm going to prepare a new stable release now. Sorry again for any inconvenience. :(

See also: https://greasyfork.org/en/forum/discussion/comment/22528#Comment_22528

**Comment by derjanb** [comment]
http://tampermonkey.net/changelog.php?version=4.0.25&show=dhdg

Waiting for the Chrome store to publish it...

**Comment by derjanb** [comment]
OK, it's published. Chrome should auto-update Tampermonkey soon, but you can also drag and drop the new release[1] to Chrome's extension page.

Sorry again for any inconvenience.

[1] https://tampermonkey.net/test/versions/stable/4.0.25/fa9adf10f06/dhdgffkkebhmkfjojejmpbldmpobfkfo_main.crx

**Comment by Martii** [comment]
> OK, it's published.

Thanks for looking into this.

> Sorry again for any inconvenience.

Mistakes happen... just glad you are receptive to investigating. Thank you so much. :)

Related to my patch at #955 ... it would seem by the CPU usage that my "forced GC" worked e.g. the running out of memory issue which is caused by overloading the CPU bandwidth... which is unexpected at this time... but a pleasant surprise. See todays graph:

![postactivity4](https://cloud.githubusercontent.com/assets/114709/14406327/e9b3e378-fe61-11e5-83de-1647781a95eb.png)

We are still spiking a bit *(see greenish as nominal and redish as spiked below)* but hopefully that will subside in about a week after everyone affected updates and when I up the lag time a little at a time.

![postactivity4a](https://cloud.githubusercontent.com/assets/114709/14406371/092865d4-fe63-11e5-8eba-76f609608891.png)

**Comment by Martii** [comment]
@derjanb 
One question though... will TM users need to reinstall to have TM update check with the Accept header or is this automatically retried after a period?

**Comment by derjanb** [comment]
@Martii 
The good news is that after more people installed the latest TM version your traffic should be back at the March level. Even if users will import a self-modified Tampermonkey settings file, the update check will now never run more than once per hour except it was triggered by a user action.
The bad news is that checking the meta data first is broken since the TM 3.12 release. :( So, thanks for bringing this up. I hope it's not a big issue since 3.12 was released 2015-10-24.

Sorry again. Some large parts of TM 4.0 were re-written from scratch and it looks like I should have done even more testing.

**Comment by Martii** [comment]
@derjanb
> Some large parts of TM 4.0 were re-written from scratch...

Hmm... now that you mention that just checked my Chromium, which I use a couple of times a day, and it had v3.12.58 installed and **not** updated... uninstalled and reinstalled from Chrome Web Store and now it's 4.0.25 ... I rarely tweak settings in Chromium but if it's not updating... hmm.

> ... more testing.

I test the browsers with OUJS almost daily with [oujs - Meta View](https://openuserjs.org/scripts/Marti/oujs_-_Meta_View)... that sends out the Accept header with the appropriate value to see if any browser is failing with XHR... it used to be GM_XHR as a Unit Test but wanted to keep it friendly across the history of browsers. One never knows what an update brings sometimes. :)

Thanks for the intel.

**Comment by derjanb** [comment]
> I rarely tweak settings in Chromium but if it's not updating... hmm.

In these days Chrome updates extensions only on re-start. This means the extension needs to be downloaded (5700000 weekly users * ~1MB) and then Chrome need to be restarted. And especially when a new major version is released then I'm releasing it only to a small but slowly increasing percentage of users. This helps to make not every TM user angry and giving a bad rating in case there are still some issues. In this case the percentage was 45% when I was notified of the update problem.

>  One never knows what an update brings sometimes. :)

I do have a lot of userscript environment tests as well. Unfortunately it's not easy to test the extension code (like updates, ```@connect```, ...), but I believe I have to mange that somehow.

**Comment by Martii** [comment]
> In these days Chrome updates extensions only on re-start.

Leaving a browser open isn't on my normal TODO list. ;) e.g. I usually close all browsers when I go AFK unless I'm monitoring via web somewhere.

> I'm releasing it only to a small but slowly increasing percentage of users.

Good to know... suppose this could have been a bit worse had everyone gotten it all at once... but we're all the better for surprises like these... hardens up sites and extensions/add-ons I think. ;) :)

**Comment by Martii** [comment]
Capping isn't working. Have one more idea to control the memory usage but will take a bit to rewrite that section. In the meantime here's the last 6 hours that I've been dealing with. Note the green smudge arrow is when we don't serve scripts with improper or missing `@updateURL`s:

![postactivity5](https://cloud.githubusercontent.com/assets/114709/14412438/16327248-ff20-11e5-91fc-60f88d9be880.png)

**Comment by Martii** [comment]
Guhh.. rebooted the server a few times and the environment variables never showed up... finally got it to work with those... however ... the project itself is BUSY right now until further notice.

**Comment by derjanb** [comment]
@Martii Is there any news on this topic. Is the amount of traffic shrinking?

**Comment by Martii** [comment]
@derjanb 
No change... I'm temporarily blocking the offenders in the firewall and working on a different solution... can't chat right now but will later.

**Comment by Martii** [comment]
@derjanb 
Still getting hammered but there is a request limiter in place now. A few brief spikes today but they were quashed. Unblocked those IPs in the firewall for the test data... seems we are more hardened now.

The 11 known IPs are the major issue... the remainder spikes from Chrome based UA's could be installs ... could not be... I don't know exactly how your TM `text/x-userscript` works when `text/x-userscript-meta` fails. Perhaps you could enlighten TM users on your "wiki" page for the UserScript metadata block keys on the logic process. There are few repeats but now those get quashed as well so the 100's of tiny stings we are getting get sent to file 13... err 429 ;) :)

![postactivity7](https://cloud.githubusercontent.com/assets/114709/14485893/2ebd4cae-0117-11e6-9ab2-8217feb0e403.png)

**Comment by Martii** [comment]
@derjanb Cc: @sizzlemctwizzle 
On an informational sidenote...

I'd like you to read http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1 as well... so when TM sends out `text/x-userscript-meta, */*` and `text/x-userscript, */*` this reads as:

> "I, TamperMonkey, prefer any Media Type but if you happen to have a userscript or meta I'd be happy with that."

So I'm not quite sure why you extended it that direction and not the other way for starters... ideally and logically it should be `text/x-userscript, text/x-userscript-meta` *(I want meta but a userscript will do too)* for meta and don't send me images, pdfs, etc. For Userscripts it should just be `text/userscript`... unless you want pictures, sound files, heck all the Media Types out there. I'm half tempted to be humorous and send TM random Media Types of Userscripts and Meta formatted in various other forms.. ;)

The more responsible thing to do on our part would to be to send a [406 (not acceptable)](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.7) response for all TamperMonkey requests. :)

**Comment by derjanb** [comment]
> the remainder spikes from Chrome based UA's could be installs ...

A little bit more traffic might be normal, because the update check now runs at long-living sessions more than once. The default interval is 24h what should quite often match the interval user's do open Chrome.

> "I, TamperMonkey, prefer any Media Type but if you happen to have a userscript or meta I'd be happy with that."

I don't see a problem here. The default header is ```*/*``` and the reason for adding the ```text/x-userscript-meta``` media type was to allow userscript sources to distinguish update checks from install requests.
The combination of both is ```text/x-userscript-meta, */*```.  OUSJ can also send ```text/x-userscript```, other script sources like Github are "allowed" to send  ```text/plain``` or whatever they want. Tampermonkey doesn't really care and accepts everything as userscript as long as it can parse it. 

> The more responsible thing to do on our part would to be to send a 406 (not acceptable) response for all TamperMonkey current malformed requests. :)

It's your site. You can do what  ever you want. ;)

**Comment by Martii** [comment]
@derjanb

**Comment by trespassersW** [comment]
Sorry for the blunt advice - what if you hang a banner on all OUJS pages -- something like "Please updade your Tampermonkey"?

**Comment by derjanb** [comment]
> So let me get this clear... you are asking us to send an Accept header for a request response?

No, everything is fine as it is.

> Chrome will continue to function on these platforms but will no longer receive updates and security fixes.

Chrome itself will not receive updates, but extensions will. This is a completely different mechanism and "Chrome will continue to function" includes downloading and therefore also updating extensions.

**Comment by Martii** [comment]
@trespassersW 
That is #957 ... I think everyone knows now that TamperMonkey made a boo-boo... but if they don't visit the site they wouldn't know anyways. One of the scripts being constantly requested is a video site... so it could be hours/days/months before they notice something is wrong if they are watching their favorite shows. So I'm not sure how much good it would do.

I thought about adding a script recall but that's a bunch of work and there might be a few ways around that... as well as since TM's intentions aren't fully public on their updating yet it could make things worse. I also thought about filing a cert had @derjanb not addressed the community with a good faith effort... but luckily we're hardened from the incident to look on the bright side. :) Room for improvement is one of my mottos still.

**Comment by Martii** [comment]
LOL ;) Hello XP

``` sh-session
(compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)
```

**Comment by Martii** [comment]
LOL!! To those watching... I'm not going to add a huge list to the acceptables... just the most common occurrences. With .user.js it's possible to send out anything so there is no point attempting to managing every possibility.

**Comment by Martii** [comment]
Just some final followup notes.

Every time, as in 100%, I release the brute force attack prevention *(see the red'ish section)* we get immediately hit hard as depicted in this usage cap:

![2016 05 29 vps usage snapshot](https://cloud.githubusercontent.com/assets/114709/15635884/b767c74e-25a9-11e6-8e77-d9933562f523.png)

This process has been performed/tested multiple time since inception. What this means is some still aren't playing nicely which could definitely include the other .user.js engines. What it also means is that it is working since the bandwidth doesn't go up and will continue to be in effect.
