### ISSUE TITLE
[i18n] Localization

### ISSUE THREAD

**Issue by GreenLunar** [OpenUserJs/OpenUserJS.org#982]
Make OUJS subjected to localization.

I would delightfully provide a translation of OUJS in my language.

**Comment by Martii** [comment]
Duplicate of #18

**Comment by Martii** [comment]
> I would delightfully provide a translation of OUJS in my language.

That would be nice when the time comes... but there are other issues in the queue to fix first. Thanks.

**Comment by GreenLunar** [comment]
Thank you.
