### ISSUE TITLE
429 error all over the place

### ISSUE THREAD

**Issue by cjmaxik** [OpenUserJs/OpenUserJS.org#999]
Hello!
What is wrong with the site? This is not OK.
http://take.ms/iY1bi

**Comment by Martii** [comment]
> What is wrong with the site?

Nothing... intended behavior.

> This is not OK.

What is your useragent and .user.js engine version right now? Some engines have known issues ... so this is a client side issue most likely.

**Comment by cjmaxik** [comment]
**User-agent** *- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.19 Safari/537.36
**.user.js engine version** - i am not sure, what is it. If you mean Tampermonkey, it is last version (4.0.25).

**Comment by Martii** [comment]
See https://github.com/OpenUserJs/OpenUserJS.org/issues/957#issuecomment-211504738 . That is one of the affected .user.js engines. It's not the only one too. Guess you've been hiding in a cave for about 3 weeks now. ;) :)

Anyhow... don't hit the site too often or it will ban you for an undisclosed period.
